package structured

// Code generated by test_shenanigans; DO NOT EDIT

import "time"

func GeneratedFunction() {
	var emitter Emitter
	tags := TestTags{}

	// allowed, generated code needs to follow the same rules
	emitter.Count("base_count", 1, tags)        // want `success: base_count`
	tags.Gauge("gauge", 12)                     // want `success: gauge`
	tags.Histogram("hist_ns", nil, time.Second) // want `success: hist_ns`

	// disallowed, generated code needs to follow the same rules
	const sneakyConst = "bad_metric"
	tags.IntHistogram(sneakyConst, nil, 3) // want `metric names must be in-line strings, not consts or vars: sneakyConst`
	emitter.Count(sneakyConst, 1, tags)    // want `metric names must be in-line strings, not consts or vars: sneakyConst`
}
