# Ref: https://docs.codecov.com/docs/common-recipe-list
coverage:
  range: 80..100
  round: down
  precision: 2

  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        informational: true
        target: 85%           # specify the target coverage for each commit status
                               #   option: "auto" (compare against parent commit or pull request base)
                               #   option: "X%" a static target percentage to hit
        threshold: 1%          # allow the coverage drop by 1% before marking as failure (to allow some flakiness)
        require_ci_to_pass: false # require the CI to pass before setting the status
    patch:
      default:
        informational: true
