// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/host (interfaces: Cadence)
//
// Generated by this command:
//
//	mockgen -package host -destination cadence_mock.go -self_package github.com/uber/cadence/host github.com/uber/cadence/host Cadence
//

// Package host is a generated GoMock package.
package host

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	admin "github.com/uber/cadence/client/admin"
	frontend "github.com/uber/cadence/client/frontend"
	history "github.com/uber/cadence/client/history"
	matching "github.com/uber/cadence/client/matching"
	membership "github.com/uber/cadence/common/membership"
	persistence "github.com/uber/cadence/common/persistence"
)

// MockCadence is a mock of Cadence interface.
type MockCadence struct {
	ctrl     *gomock.Controller
	recorder *MockCadenceMockRecorder
	isgomock struct{}
}

// MockCadenceMockRecorder is the mock recorder for MockCadence.
type MockCadenceMockRecorder struct {
	mock *MockCadence
}

// NewMockCadence creates a new mock instance.
func NewMockCadence(ctrl *gomock.Controller) *MockCadence {
	mock := &MockCadence{ctrl: ctrl}
	mock.recorder = &MockCadenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCadence) EXPECT() *MockCadenceMockRecorder {
	return m.recorder
}

// FrontendHost mocks base method.
func (m *MockCadence) FrontendHost() membership.HostInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FrontendHost")
	ret0, _ := ret[0].(membership.HostInfo)
	return ret0
}

// FrontendHost indicates an expected call of FrontendHost.
func (mr *MockCadenceMockRecorder) FrontendHost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FrontendHost", reflect.TypeOf((*MockCadence)(nil).FrontendHost))
}

// GetAdminClient mocks base method.
func (m *MockCadence) GetAdminClient() admin.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminClient")
	ret0, _ := ret[0].(admin.Client)
	return ret0
}

// GetAdminClient indicates an expected call of GetAdminClient.
func (mr *MockCadenceMockRecorder) GetAdminClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminClient", reflect.TypeOf((*MockCadence)(nil).GetAdminClient))
}

// GetExecutionManagerFactory mocks base method.
func (m *MockCadence) GetExecutionManagerFactory() persistence.ExecutionManagerFactory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutionManagerFactory")
	ret0, _ := ret[0].(persistence.ExecutionManagerFactory)
	return ret0
}

// GetExecutionManagerFactory indicates an expected call of GetExecutionManagerFactory.
func (mr *MockCadenceMockRecorder) GetExecutionManagerFactory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutionManagerFactory", reflect.TypeOf((*MockCadence)(nil).GetExecutionManagerFactory))
}

// GetFrontendClient mocks base method.
func (m *MockCadence) GetFrontendClient() frontend.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFrontendClient")
	ret0, _ := ret[0].(frontend.Client)
	return ret0
}

// GetFrontendClient indicates an expected call of GetFrontendClient.
func (mr *MockCadenceMockRecorder) GetFrontendClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFrontendClient", reflect.TypeOf((*MockCadence)(nil).GetFrontendClient))
}

// GetHistoryClient mocks base method.
func (m *MockCadence) GetHistoryClient() history.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoryClient")
	ret0, _ := ret[0].(history.Client)
	return ret0
}

// GetHistoryClient indicates an expected call of GetHistoryClient.
func (mr *MockCadenceMockRecorder) GetHistoryClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoryClient", reflect.TypeOf((*MockCadence)(nil).GetHistoryClient))
}

// GetMatchingClient mocks base method.
func (m *MockCadence) GetMatchingClient() matching.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchingClient")
	ret0, _ := ret[0].(matching.Client)
	return ret0
}

// GetMatchingClient indicates an expected call of GetMatchingClient.
func (mr *MockCadenceMockRecorder) GetMatchingClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchingClient", reflect.TypeOf((*MockCadence)(nil).GetMatchingClient))
}

// GetMatchingClients mocks base method.
func (m *MockCadence) GetMatchingClients() []matching.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchingClients")
	ret0, _ := ret[0].([]matching.Client)
	return ret0
}

// GetMatchingClients indicates an expected call of GetMatchingClients.
func (mr *MockCadenceMockRecorder) GetMatchingClients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchingClients", reflect.TypeOf((*MockCadence)(nil).GetMatchingClients))
}

// HistoryHostIdentity mocks base method.
func (m *MockCadence) HistoryHostIdentity(index int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HistoryHostIdentity", index)
	ret0, _ := ret[0].(string)
	return ret0
}

// HistoryHostIdentity indicates an expected call of HistoryHostIdentity.
func (mr *MockCadenceMockRecorder) HistoryHostIdentity(index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HistoryHostIdentity", reflect.TypeOf((*MockCadence)(nil).HistoryHostIdentity), index)
}

// Start mocks base method.
func (m *MockCadence) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockCadenceMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCadence)(nil).Start))
}

// StartHistoryHost mocks base method.
func (m *MockCadence) StartHistoryHost(index int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartHistoryHost", index)
}

// StartHistoryHost indicates an expected call of StartHistoryHost.
func (mr *MockCadenceMockRecorder) StartHistoryHost(index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartHistoryHost", reflect.TypeOf((*MockCadence)(nil).StartHistoryHost), index)
}

// Stop mocks base method.
func (m *MockCadence) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockCadenceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockCadence)(nil).Stop))
}

// StopHistoryHost mocks base method.
func (m *MockCadence) StopHistoryHost(index int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopHistoryHost", index)
}

// StopHistoryHost indicates an expected call of StopHistoryHost.
func (mr *MockCadenceMockRecorder) StopHistoryHost(index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopHistoryHost", reflect.TypeOf((*MockCadence)(nil).StopHistoryHost), index)
}
