// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/host (interfaces: HostController)
//
// Generated by this command:
//
//	mockgen -package host -destination host_controller_mock.go -self_package github.com/uber/cadence/host github.com/uber/cadence/host HostController
//

// Package host is a generated GoMock package.
package host

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHostController is a mock of HostController interface.
type MockHostController struct {
	ctrl     *gomock.Controller
	recorder *MockHostControllerMockRecorder
	isgomock struct{}
}

// MockHostControllerMockRecorder is the mock recorder for MockHostController.
type MockHostControllerMockRecorder struct {
	mock *MockHostController
}

// NewMockHostController creates a new mock instance.
func NewMockHostController(ctrl *gomock.Controller) *MockHostController {
	mock := &MockHostController{ctrl: ctrl}
	mock.recorder = &MockHostControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostController) EXPECT() *MockHostControllerMockRecorder {
	return m.recorder
}

// HostIdentity mocks base method.
func (m *MockHostController) HostIdentity(index int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HostIdentity", index)
	ret0, _ := ret[0].(string)
	return ret0
}

// HostIdentity indicates an expected call of HostIdentity.
func (mr *MockHostControllerMockRecorder) HostIdentity(index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HostIdentity", reflect.TypeOf((*MockHostController)(nil).HostIdentity), index)
}

// StartHost mocks base method.
func (m *MockHostController) StartHost(index int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartHost", index)
}

// StartHost indicates an expected call of StartHost.
func (mr *MockHostControllerMockRecorder) StartHost(index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartHost", reflect.TypeOf((*MockHostController)(nil).StartHost), index)
}

// StopHost mocks base method.
func (m *MockHostController) StopHost(index int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopHost", index)
}

// StopHost indicates an expected call of StopHost.
func (mr *MockHostControllerMockRecorder) StopHost(index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopHost", reflect.TypeOf((*MockHostController)(nil).StopHost), index)
}
