steps:
  - label: ":golang: unit test"
    agents:
      queue: "workers"
      docker: "*"
    command: "make cover_ci"
    plugins:
      - docker-compose#v3.0.0:
          run: unit-test
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration test with cassandra"
    agents:
      queue: "workers"
      docker: "*"
    command: "make cover_integration_ci"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-compose#v3.0.0:
          run: integration-test-cassandra
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration test events v2 with cassandra"
    agents:
      queue: "workers"
      docker: "*"
    command: "make cover_integration_ci EVENTSV2=true"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-compose#v3.0.0:
          run: integration-test-cassandra
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration xdc test with cassandra"
    agents:
      queue: "workers"
      docker: "*"
    command: "make cover_xdc_ci"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-compose#v3.0.0:
          run: integration-test-xdc-cassandra
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration test with mysql"
    agents:
      queue: "workers"
      docker: "*"
    command: "make cover_integration_ci"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-compose#v3.0.0:
          run: integration-test-mysql
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration test events v2 with mysql"
    agents:
      queue: "workers"
      docker: "*"
    command: "make cover_integration_ci EVENTSV2=true"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-compose#v3.0.0:
          run: integration-test-mysql
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration xdc test with mysql"
    agents:
      queue: "workers"
      docker: "*"
    command: "make cover_xdc_ci"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-compose#v3.0.0:
          run: integration-test-xdc-mysql
          config: docker/buildkite/docker-compose.yml

  - wait

  - label: ":docker: build and push master"
    agents:
      queue: "workers"
      docker: "*"
    command: "scripts/buildkite/docker-push.sh"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-login#v2.0.1:
          username: ubercadence
          password-env: DOCKER_LOGIN_PASSWORD