steps:
  - label: ":golang:"
    agents:
      queue: "*"
      docker: "*"
    command: "make cover_integration_ci"
    plugins:
      - docker-compose#v3.0.0:
          run: integrationtest
          config: docker/buildkite/docker-compose.yml
