steps:
  - label: ":golang: unit test"
    agents:
      queue: "*"
      docker: "*"
    plugins:
      - docker-compose#v3.0.0:
          run: unit-test
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration test"
      agents:
        queue: "*"
        docker: "*"
      plugins:
        - docker-compose#v3.0.0:
            run: integration-test
            config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration xdc test"
      agents:
        queue: "*"
        docker: "*"
      plugins:
        - docker-compose#v3.0.0:
            run: integration-test-xdc
            config: docker/buildkite/docker-compose.yml
