{
 "title": "Cadence-Frontend",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values(activity_end_to_end_latency_bucket,domain)"
    }
   },
   {
    "name": "services",
    "label": "services",
    "query": {
     "query": "label_values(cadence_requests,cadence_service)"
    }
   },
   { "name": "latency", "label": "latency", "query": "p99,upper,mean,median,lower" }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Counts Per API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{cadence_service=\"cadence_frontend\", domain=\"$domain\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_errors{cadence_service=\"cadence_frontend\", domain=\"$domain\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (rate(cadence_errors_entity_not_exists{cadence_service=\"cadence_frontend\", domain=\"$domain\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (rate(cadence_errors_per_tl{cadence_service=\"cadence_frontend\", domain=\"$domain\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(cadence_PollForActivityTask_cadence_error{cadence_service=\"cadence_frontend\", domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Counts Per API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "rate(cadence_errors{cadence_service=\"cadence_frontend\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Vs Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{cadence_service=\"cadence_frontend\", domain=\"$domain\"}[$__rate_interval]))",
       "legendFormat": "{{operation}} (request)"
      },
      {
       "expr": "sum by(operation) (rate(cadence_errors{cadence_service=\"cadence_frontend\", domain=\"$domain\"}[$__rate_interval]))",
       "legendFormat": "{{operation}} (error)"
      }
     ]
    },
    {
     "title": "Frontend API Latencies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(cadence_latency_bucket{cadence_service=\"cadence_frontend\", domain=\"$domain\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Frontend-Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Frontend Client Request Vs Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(cadence_client_errors{cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
     "legendFormat": "{{operation}} (request)"
    },
    {
     "expr": "sum by(operation) (rate(cadence_client_requests{cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
     "legendFormat": "{{operation}} (error)"
    }
   ]
  },
  {
   "title": "Frontend Client Request Counts Per API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(cadence_client_requests{cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Client API Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(cadence_client_latency_bucket{cadence_service=\"cadence_frontend\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Client Request Counts Per API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(cadence_client_errors{cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "StartWorfklowExecution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{operation=\"StartWorkflowExecution\", domain=\"$domain\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "StartWorkflowExection Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(cadence_latency_bucket{operation=\"StartWorkflowExecution\", domain=\"$domain\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests per operation per task",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum by(operation, tasklist) (rate(cadence_requests_per_tl{cadence_service=\"$services\", domain=\"$domain\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workflow success per operation per task",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum by(operation, tasklist) (rate(workflow_success{cadence_service=\"$services\", domain=\"$domain\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Respond Activity task completed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{operation=\"RespondActivityTaskCompleted\", cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RespondActivity Task Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(cadence_latency_bucket{operation=\"RespondActivityTaskCompleted\", cadence_service=\"cadence_frontend\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PollForActivityTask",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum by(TaskList) (rate(cadence_PollForActivityTask_cadence_request[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PollForActivityTask Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(cadence_latency_bucket{operation=\"PollForActivityTask\", cadence_service=\"cadence_frontend\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PollForDecisionTask",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "sum by(TaskList) (rate(cadence_PollForDecisionTask_cadence_request[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PollForDecisionTask Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(cadence_latency_bucket{operation=\"PollForDecisionTask\", cadence_service=\"cadence_frontend\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DescribeDomain",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{operation=\"DescribeDomain\", cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DescribeDomain Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(cadence_latency_bucket{operation=\"DescribeDomain\", cadence_service=\"cadence_frontend\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GetWorkflowExecutionHistory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{operation=\"GetWorkflowExecutionHistory\", cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CancelWorkflowExecution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{operation=\"CancelWorkflowExecution\", cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TerminateWorkflowExecution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{operation=\"TerminateWorkflowExecution\", cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RegisterDomain",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{operation=\"RegisterDomain\", cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DescribeDomain",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{operation=\"DescribeDomain\", cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "UpdateDomain",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{operation=\"UpdateDomain\", cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DepricateDomain",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{operation=\"DepricateDomain\", cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AddDecisionTask",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{operation=\"AddDecisionTask\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Persistence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Requests Vs Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(persistence_requests{cadence_service=\"$services\"}[$__rate_interval]))",
     "legendFormat": "{{operation}} (request)"
    },
    {
     "expr": "sum by(operation) (rate(persistence_errors{cadence_service=\"$services\"}[$__rate_interval]))",
     "legendFormat": "{{operation}} (error)"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(persistence_requests{cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operation Latencies p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, avg by(operation, le) (rate(persistence_latency_bucket{cadence_service=\"$services\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(operation) (rate(persistence_errors_entity_not_exists{cadence_service=\"$services\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall Query Sizes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 317 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(event_blob_size_bucket{cadence_service=\"cadence_frontend\", domain=\"$domain\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Sizes by Domain",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 317 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, domain) (rate(event_blob_size_bucket{cadence_service=\"cadence_frontend\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Authorization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Authorization latency per API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 318 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(cadence_authorization_latency_bucket{cadence_service=\"cadence_frontend\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Gc Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Memory Allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 319 },
     "targets": [
      {
       "expr": "sum by(cadence_service) (rate(memory_allocated{cadence_service=\"$services\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC Num",
     "type": "timeseries",
     "description": "NumGC is the number of completed GC cycles.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 319 },
     "targets": [
      {
       "expr": "sum by(cadence_service) (rate(memory_num_gc{cadence_service=\"$services\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 327 },
     "targets": [
      {
       "expr": "sum by(cadence_service) (rate(num_goroutines{cadence_service=\"$services\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap in Use (HeapAlloc)",
     "type": "timeseries",
     "description": "HeapInuse is bytes in in-use spans.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 327 },
     "targets": [
      {
       "expr": "sum by(cadence_service) (rate(memory_heapinuse{cadence_service=\"$services\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap Available (HeapIdle)",
     "type": "timeseries",
     "description": "HeapIdle is bytes in idle (unused) spans.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 335 },
     "targets": [
      {
       "expr": "sum by(cadence_service) (rate(memory_heapidle{cadence_service=\"$services\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stack In use",
     "type": "timeseries",
     "description": "Bytes of stack memory obtained from the OS. Plus any memory obtained directly from the OS for OS thread stacks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 335 },
     "targets": [
      {
       "expr": "sum by(cadence_service) (rate(memory_stack{cadence_service=\"$services\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "GetReplicationMessage Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(cadence_requests{operation=\"GetReplicationMessage\", \"$services\"=\"$services\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GetDomainReplicationMessage Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(cadence_requests{operation=\"GetDomainReplicationMessage\", \"$services\"=\"$services\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GetReplicationMessage Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(cadence_latency_bucket{operation=\"GetReplicationMessage\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GetDomainReplicationMessage Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(cadence_latency_bucket{operation=\"GetDomainReplicationMessage\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}