// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/common/dynamicconfig/provider (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -package=provider -destination=provider_mock.go -self_package=github.com/uber/cadence/common/dynamicconfig/provider github.com/uber/cadence/common/dynamicconfig/provider Provider
//

// Package provider is a generated GoMock package.
package provider

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	dynamicconfig "github.com/uber/cadence/common/dynamicconfig"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetClient mocks base method.
func (m *MockProvider) GetClient(name string) (dynamicconfig.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", name)
	ret0, _ := ret[0].(dynamicconfig.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockProviderMockRecorder) GetClient(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockProvider)(nil).GetClient), name)
}
