services:
  cadence:
    image: ${CADENCE_IMAGE:-cadence-sqlite-auto-setup:test}
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        TARGET: auto-setup
    environment:
      DB: sqlite
      DBNAME: /tmp/cadence.db
      VISIBILITY_DBNAME: /tmp/cadence_visibility.db
