services:
  cadence:
    image: ${CADENCE_IMAGE:-cadence-sqlite-auto-setup:test}
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        TARGET: auto-setup
    environment:
      DB: sqlite
      DBNAME: /tmp/cadence.db
      VISIBILITY_DBNAME: /tmp/cadence_visibility.db
    ports:
      - "7933:7933"
      - "7833:7833"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
