frontend.enableClientVersionCheck:
- value: true
  constraints: {}
system.minRetentionDays:
- value: 0
  constraints: {}
history.EnableConsistentQueryByDomain:
- value: true
  constraints: {}
history.enableCrossClusterOperations:
- value: true
  constraints: {}
history.useNewInitialFailoverVersion:
- value: true
  constraints: {}
history.useNewInitialFailoverVersion:
- value: true
  constraints: {}
system.allIsolationGroups:
- value:
  - "zone-1"
  - "zone-2"
  - "zone-3"
  constraints: {}
system.enableTasklistIsolation:
- value: true
