frontend.enableClientVersionCheck:
- value: true
  constraints: {}
system.minRetentionDays:
- value: 0
  constraints: {}
history.EnableConsistentQueryByDomain:
- value: true
  constraints: {}
history.enableForceScheduleNewDecision:
- value: true
  constraints: {}
