version: '3'
services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"

  cadence:
    image: ubercadence/server:master-auto-setup
    ports:
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cassandra

  hello-world-sample:
    build:
      context: .
      dockerfile: hello-world/Dockerfile
    environment:
      - "CADENCE_HOST=cadence"
      - "CADENCE_PORT=7933"
    depends_on:
      - cadence