// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package ratelimited

import (
	"context"

	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
)

// ratelimitedAsyncWorkflowQueueManager implements _sourcePersistence.AsyncWorkflowQueueManager interface instrumented with rate limiter.
type ratelimitedAsyncWorkflowQueueManager struct {
	wrapped      _sourcePersistence.AsyncWorkflowQueueManager
	rateLimiter  quotas.Limiter
	callerBypass quotas.CallerBypass
}

// NewAsyncWorkflowQueueManager creates a new instance of AsyncWorkflowQueueManager with ratelimiter.
func NewAsyncWorkflowQueueManager(
	wrapped persistence.AsyncWorkflowQueueManager,
	rateLimiter quotas.Limiter,
	callerBypass quotas.CallerBypass,
) persistence.AsyncWorkflowQueueManager {
	return &ratelimitedAsyncWorkflowQueueManager{
		wrapped:      wrapped,
		rateLimiter:  rateLimiter,
		callerBypass: callerBypass,
	}
}

func (c *ratelimitedAsyncWorkflowQueueManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedAsyncWorkflowQueueManager) EnqueueAsyncWorkflowMessage(ctx context.Context, request *_sourcePersistence.EnqueueAsyncWorkflowMessageRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.EnqueueAsyncWorkflowMessage(ctx, request)
}

func (c *ratelimitedAsyncWorkflowQueueManager) EnqueueAsyncWorkflowMessageToDLQ(ctx context.Context, request *_sourcePersistence.EnqueueAsyncWorkflowMessageToDLQRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.EnqueueAsyncWorkflowMessageToDLQ(ctx, request)
}

func (c *ratelimitedAsyncWorkflowQueueManager) GetAsyncWorkflowAckLevels(ctx context.Context, request *_sourcePersistence.GetAsyncWorkflowAckLevelsRequest) (gp1 *_sourcePersistence.GetAsyncWorkflowAckLevelsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetAsyncWorkflowAckLevels(ctx, request)
}

func (c *ratelimitedAsyncWorkflowQueueManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *ratelimitedAsyncWorkflowQueueManager) RangeDeleteAsyncWorkflowMessages(ctx context.Context, request *_sourcePersistence.RangeDeleteAsyncWorkflowMessagesRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.RangeDeleteAsyncWorkflowMessages(ctx, request)
}

func (c *ratelimitedAsyncWorkflowQueueManager) RangeDeleteAsyncWorkflowMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.RangeDeleteAsyncWorkflowMessagesFromDLQRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.RangeDeleteAsyncWorkflowMessagesFromDLQ(ctx, request)
}

func (c *ratelimitedAsyncWorkflowQueueManager) ReadAsyncWorkflowMessages(ctx context.Context, request *_sourcePersistence.ReadAsyncWorkflowMessagesRequest) (rp1 *_sourcePersistence.ReadAsyncWorkflowMessagesResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ReadAsyncWorkflowMessages(ctx, request)
}

func (c *ratelimitedAsyncWorkflowQueueManager) ReadAsyncWorkflowMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.ReadAsyncWorkflowMessagesFromDLQRequest) (rp1 *_sourcePersistence.ReadAsyncWorkflowMessagesFromDLQResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ReadAsyncWorkflowMessagesFromDLQ(ctx, request)
}

func (c *ratelimitedAsyncWorkflowQueueManager) UpdateAsyncWorkflowAckLevel(ctx context.Context, request *_sourcePersistence.UpdateAsyncWorkflowAckLevelRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateAsyncWorkflowAckLevel(ctx, request)
}
