// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package ratelimited

import (
	"context"

	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
)

// ratelimitedDomainAuditManager implements _sourcePersistence.DomainAuditManager interface instrumented with rate limiter.
type ratelimitedDomainAuditManager struct {
	wrapped      _sourcePersistence.DomainAuditManager
	rateLimiter  quotas.Limiter
	callerBypass quotas.CallerBypass
}

// NewDomainAuditManager creates a new instance of DomainAuditManager with ratelimiter.
func NewDomainAuditManager(
	wrapped persistence.DomainAuditManager,
	rateLimiter quotas.Limiter,
	callerBypass quotas.CallerBypass,
) persistence.DomainAuditManager {
	return &ratelimitedDomainAuditManager{
		wrapped:      wrapped,
		rateLimiter:  rateLimiter,
		callerBypass: callerBypass,
	}
}

func (c *ratelimitedDomainAuditManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedDomainAuditManager) CreateDomainAuditLog(ctx context.Context, request *_sourcePersistence.CreateDomainAuditLogRequest) (cp1 *_sourcePersistence.CreateDomainAuditLogResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CreateDomainAuditLog(ctx, request)
}

func (c *ratelimitedDomainAuditManager) GetDomainAuditLogs(ctx context.Context, request *_sourcePersistence.GetDomainAuditLogsRequest) (gp1 *_sourcePersistence.GetDomainAuditLogsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetDomainAuditLogs(ctx, request)
}

func (c *ratelimitedDomainAuditManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}
