// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package ratelimited

import (
	"context"

	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
)

// ratelimitedSemaphoreMetadataManager implements _sourcePersistence.SemaphoreMetadataManager interface instrumented with rate limiter.
type ratelimitedSemaphoreMetadataManager struct {
	wrapped      _sourcePersistence.SemaphoreMetadataManager
	rateLimiter  quotas.Limiter
	callerBypass quotas.CallerBypass
}

// NewSemaphoreMetadataManager creates a new instance of SemaphoreMetadataManager with ratelimiter.
func NewSemaphoreMetadataManager(
	wrapped persistence.SemaphoreMetadataManager,
	rateLimiter quotas.Limiter,
	callerBypass quotas.CallerBypass,
) persistence.SemaphoreMetadataManager {
	return &ratelimitedSemaphoreMetadataManager{
		wrapped:      wrapped,
		rateLimiter:  rateLimiter,
		callerBypass: callerBypass,
	}
}

func (c *ratelimitedSemaphoreMetadataManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedSemaphoreMetadataManager) CreateSemaphore(ctx context.Context, request *_sourcePersistence.CreateSemaphoreRequest) (cp1 *_sourcePersistence.CreateSemaphoreResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CreateSemaphore(ctx, request)
}

func (c *ratelimitedSemaphoreMetadataManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *ratelimitedSemaphoreMetadataManager) GetSemaphore(ctx context.Context, request *_sourcePersistence.GetSemaphoreRequest) (gp1 *_sourcePersistence.GetSemaphoreResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetSemaphore(ctx, request)
}

func (c *ratelimitedSemaphoreMetadataManager) ListSemaphores(ctx context.Context, request *_sourcePersistence.ListSemaphoresRequest) (lp1 *_sourcePersistence.ListSemaphoresResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListSemaphores(ctx, request)
}
