cassandra:
  name: "cassandra-cluster"
  hosts: "127.0.0.1"
  keyspace: "cadence"
  visibilityKeyspace: "cadence_visibility"
  consistency: "One"
  numHistoryShards: 1

persistence:
  databases:
    sql1:
      sql:
        name: "foo"
        user: "bar"
    cas1:
      cassandra:
        keyspace: "sql1"

  managers:
    metadata: "cas1"
    visibility: "sql1"
    historyt: "cas1"

ringpop:
  name: cadence
  bootstrapMode: hosts
  bootstrapHosts: ["127.0.0.1:7933", "127.0.0.1:7934", "127.0.0.1:7935"]
  maxJoinDuration: 30s

services:
  frontend:
    rpc:
      port: 7933
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7936

  matching:
    rpc:
      port: 7935
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7938

  history:
    rpc:
      port: 7934
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7937

clustersInfo:
  enableGlobalDomain: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInitialFailoverVersion:
    active: 0
    standby: 1
