services:
  frontend:
    rpc:
      port: 7933
      grpcPort: 7833
      bindOnLocalHost: true
      grpcMaxMsgSize: 33554432
      # enable HTTP server, allow to call Start worfklow using HTTP API
      # Use curl to start a workflow:
      #  curl  http://0.0.0.0:8800 \
      #   -H 'context-ttl-ms: 2000' \
      #   -H 'rpc-caller: rpc-client-name' \
      #   -H 'rpc-service: cadence-frontend' \
      #   -H 'rpc-encoding: json' \
      #   -H 'rpc-procedure: uber.cadence.api.v1.WorkflowAPI::StartWorkflowExecution' \
      #   -X POST --data @data.json
      #  Where data.json content looks something like this:
      #  {
      #    "domain": "samples-domain",
      #    "workflowId": "workflowid123",
      #    "execution_start_to_close_timeout": "11s",
      #    "task_start_to_close_timeout": "10s",
      #    "workflowType": {
      #      "name": "workflow_type"
      #    },
      #    "taskList": {
      #      "name": "tasklist-name"
      #    },
      #   "identity": "My custom identity",
      #    "requestId": "4D1E4058-6FCF-4BA8-BF16-8FA8B02F9651"
      #  }
      http:
        port: 8800
        procedures:
          - uber.cadence.api.v1.WorkflowAPI::StartWorkflowExecution
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7936
