persistence:
  advancedVisibilityStore: pinot-visibility
  datastores:
    pinot-visibility:
      pinot:
        url:
          scheme: "http"
          host: "127.0.0.1:2181"
        cluster: pinot-test

kafka:
  tls:
    enabled: false
  clusters:
    test:
      brokers:
        - kafka:9093
  topics:
    cadence-visibility-pinot:
      cluster: test
    cadence-visibility-pinot-dlq:
      cluster: test
  applications:
    visibility:
      topic: cadence-visibility-pinot
      dlq-topic: cadence-visibility-pinot-dlq

dynamicconfig:
  client: filebased
  filebased:
    filepath: "config/dynamicconfig/development_es.yaml"