// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -package spectatorclient -source client.go -destination interface_mock.go . Spectator
//

// Package spectatorclient is a generated GoMock package.
package spectatorclient

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSpectator is a mock of Spectator interface.
type MockSpectator struct {
	ctrl     *gomock.Controller
	recorder *MockSpectatorMockRecorder
	isgomock struct{}
}

// MockSpectatorMockRecorder is the mock recorder for MockSpectator.
type MockSpectatorMockRecorder struct {
	mock *MockSpectator
}

// NewMockSpectator creates a new mock instance.
func NewMockSpectator(ctrl *gomock.Controller) *MockSpectator {
	mock := &MockSpectator{ctrl: ctrl}
	mock.recorder = &MockSpectatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpectator) EXPECT() *MockSpectatorMockRecorder {
	return m.recorder
}

// GetExecutors mocks base method.
func (m *MockSpectator) GetExecutors() map[string]*ShardOwner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutors")
	ret0, _ := ret[0].(map[string]*ShardOwner)
	return ret0
}

// GetExecutors indicates an expected call of GetExecutors.
func (mr *MockSpectatorMockRecorder) GetExecutors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutors", reflect.TypeOf((*MockSpectator)(nil).GetExecutors))
}

// GetShardOwner mocks base method.
func (m *MockSpectator) GetShardOwner(ctx context.Context, shardKey string) (*ShardOwner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShardOwner", ctx, shardKey)
	ret0, _ := ret[0].(*ShardOwner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShardOwner indicates an expected call of GetShardOwner.
func (mr *MockSpectatorMockRecorder) GetShardOwner(ctx, shardKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShardOwner", reflect.TypeOf((*MockSpectator)(nil).GetShardOwner), ctx, shardKey)
}

// Start mocks base method.
func (m *MockSpectator) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockSpectatorMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSpectator)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockSpectator) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockSpectatorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSpectator)(nil).Stop))
}

// Subscribe mocks base method.
func (m *MockSpectator) Subscribe(subscriberName string) (<-chan struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", subscriberName)
	ret0, _ := ret[0].(<-chan struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockSpectatorMockRecorder) Subscribe(subscriberName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockSpectator)(nil).Subscribe), subscriberName)
}

// Unsubscribe mocks base method.
func (m *MockSpectator) Unsubscribe(subscriberName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", subscriberName)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockSpectatorMockRecorder) Unsubscribe(subscriberName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockSpectator)(nil).Unsubscribe), subscriberName)
}
