// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/common/elasticsearch/bulk (interfaces: GenericBulkableRequest)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/GenericBulkableRequest.go github.com/uber/cadence/common/elasticsearch/bulk GenericBulkableRequest
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGenericBulkableRequest is a mock of GenericBulkableRequest interface.
type MockGenericBulkableRequest struct {
	ctrl     *gomock.Controller
	recorder *MockGenericBulkableRequestMockRecorder
	isgomock struct{}
}

// MockGenericBulkableRequestMockRecorder is the mock recorder for MockGenericBulkableRequest.
type MockGenericBulkableRequestMockRecorder struct {
	mock *MockGenericBulkableRequest
}

// NewMockGenericBulkableRequest creates a new mock instance.
func NewMockGenericBulkableRequest(ctrl *gomock.Controller) *MockGenericBulkableRequest {
	mock := &MockGenericBulkableRequest{ctrl: ctrl}
	mock.recorder = &MockGenericBulkableRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenericBulkableRequest) EXPECT() *MockGenericBulkableRequestMockRecorder {
	return m.recorder
}

// Source mocks base method.
func (m *MockGenericBulkableRequest) Source() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Source")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Source indicates an expected call of Source.
func (mr *MockGenericBulkableRequestMockRecorder) Source() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Source", reflect.TypeOf((*MockGenericBulkableRequest)(nil).Source))
}

// String mocks base method.
func (m *MockGenericBulkableRequest) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockGenericBulkableRequestMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockGenericBulkableRequest)(nil).String))
}
