// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/metered.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package metered

import (
	"context"

	"github.com/uber/cadence/common/config"
	"github.com/uber/cadence/common/log"
	"github.com/uber/cadence/common/metrics"
	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
)

// meteredAsyncWorkflowQueueManager implements _sourcePersistence.AsyncWorkflowQueueManager interface instrumented with rate limiter.
type meteredAsyncWorkflowQueueManager struct {
	base
	wrapped _sourcePersistence.AsyncWorkflowQueueManager
}

// NewAsyncWorkflowQueueManager creates a new instance of AsyncWorkflowQueueManager with ratelimiter.
func NewAsyncWorkflowQueueManager(
	wrapped persistence.AsyncWorkflowQueueManager,
	metricClient metrics.Client,
	logger log.Logger,
	cfg *config.Persistence,
) persistence.AsyncWorkflowQueueManager {
	return &meteredAsyncWorkflowQueueManager{
		wrapped: wrapped,
		base: base{
			metricClient:                  metricClient,
			logger:                        logger,
			enableLatencyHistogramMetrics: cfg.EnablePersistenceLatencyHistogramMetrics,
			hostName:                      cfg.HostName,
		},
	}
}

func (c *meteredAsyncWorkflowQueueManager) Close() {
	c.wrapped.Close()
	return
}

func (c *meteredAsyncWorkflowQueueManager) EnqueueAsyncWorkflowMessage(ctx context.Context, request *_sourcePersistence.EnqueueAsyncWorkflowMessageRequest) (err error) {
	op := func() error {
		err = c.wrapped.EnqueueAsyncWorkflowMessage(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.EnqueueAsyncWorkflowMessage", request, err, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceEnqueueAsyncWorkflowMessageScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredAsyncWorkflowQueueManager) EnqueueAsyncWorkflowMessageToDLQ(ctx context.Context, request *_sourcePersistence.EnqueueAsyncWorkflowMessageToDLQRequest) (err error) {
	op := func() error {
		err = c.wrapped.EnqueueAsyncWorkflowMessageToDLQ(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.EnqueueAsyncWorkflowMessageToDLQ", request, err, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceEnqueueAsyncWorkflowMessageToDLQScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredAsyncWorkflowQueueManager) GetAsyncWorkflowAckLevels(ctx context.Context, request *_sourcePersistence.GetAsyncWorkflowAckLevelsRequest) (gp1 *_sourcePersistence.GetAsyncWorkflowAckLevelsResponse, err error) {
	op := func() error {
		gp1, err = c.wrapped.GetAsyncWorkflowAckLevels(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.GetAsyncWorkflowAckLevels", request, gp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceGetAsyncWorkflowAckLevelsScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredAsyncWorkflowQueueManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *meteredAsyncWorkflowQueueManager) RangeDeleteAsyncWorkflowMessages(ctx context.Context, request *_sourcePersistence.RangeDeleteAsyncWorkflowMessagesRequest) (err error) {
	op := func() error {
		err = c.wrapped.RangeDeleteAsyncWorkflowMessages(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.RangeDeleteAsyncWorkflowMessages", request, err, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceRangeDeleteAsyncWorkflowMessagesScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredAsyncWorkflowQueueManager) RangeDeleteAsyncWorkflowMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.RangeDeleteAsyncWorkflowMessagesFromDLQRequest) (err error) {
	op := func() error {
		err = c.wrapped.RangeDeleteAsyncWorkflowMessagesFromDLQ(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.RangeDeleteAsyncWorkflowMessagesFromDLQ", request, err, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceRangeDeleteAsyncWorkflowMessagesFromDLQScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredAsyncWorkflowQueueManager) ReadAsyncWorkflowMessages(ctx context.Context, request *_sourcePersistence.ReadAsyncWorkflowMessagesRequest) (rp1 *_sourcePersistence.ReadAsyncWorkflowMessagesResponse, err error) {
	op := func() error {
		rp1, err = c.wrapped.ReadAsyncWorkflowMessages(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.ReadAsyncWorkflowMessages", request, rp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceReadAsyncWorkflowMessagesScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredAsyncWorkflowQueueManager) ReadAsyncWorkflowMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.ReadAsyncWorkflowMessagesFromDLQRequest) (rp1 *_sourcePersistence.ReadAsyncWorkflowMessagesFromDLQResponse, err error) {
	op := func() error {
		rp1, err = c.wrapped.ReadAsyncWorkflowMessagesFromDLQ(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.ReadAsyncWorkflowMessagesFromDLQ", request, rp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceReadAsyncWorkflowMessagesFromDLQScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredAsyncWorkflowQueueManager) UpdateAsyncWorkflowAckLevel(ctx context.Context, request *_sourcePersistence.UpdateAsyncWorkflowAckLevelRequest) (err error) {
	op := func() error {
		err = c.wrapped.UpdateAsyncWorkflowAckLevel(ctx, request)
		c.emptyMetric("AsyncWorkflowQueueManager.UpdateAsyncWorkflowAckLevel", request, err, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceUpdateAsyncWorkflowAckLevelScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}
