// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/metered.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package metered

import (
	"context"

	"github.com/uber/cadence/common/config"
	"github.com/uber/cadence/common/log"
	"github.com/uber/cadence/common/metrics"
	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
)

// meteredDomainAuditManager implements _sourcePersistence.DomainAuditManager interface instrumented with rate limiter.
type meteredDomainAuditManager struct {
	base
	wrapped _sourcePersistence.DomainAuditManager
}

// NewDomainAuditManager creates a new instance of DomainAuditManager with ratelimiter.
func NewDomainAuditManager(
	wrapped persistence.DomainAuditManager,
	metricClient metrics.Client,
	logger log.Logger,
	cfg *config.Persistence,
) persistence.DomainAuditManager {
	return &meteredDomainAuditManager{
		wrapped: wrapped,
		base: base{
			metricClient:                  metricClient,
			logger:                        logger,
			enableLatencyHistogramMetrics: cfg.EnablePersistenceLatencyHistogramMetrics,
			hostName:                      cfg.HostName,
		},
	}
}

func (c *meteredDomainAuditManager) Close() {
	c.wrapped.Close()
	return
}

func (c *meteredDomainAuditManager) CreateDomainAuditLog(ctx context.Context, request *_sourcePersistence.CreateDomainAuditLogRequest) (cp1 *_sourcePersistence.CreateDomainAuditLogResponse, err error) {
	op := func() error {
		cp1, err = c.wrapped.CreateDomainAuditLog(ctx, request)
		c.emptyMetric("DomainAuditManager.CreateDomainAuditLog", request, cp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceCreateDomainAuditLogScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredDomainAuditManager) GetDomainAuditLogs(ctx context.Context, request *_sourcePersistence.GetDomainAuditLogsRequest) (gp1 *_sourcePersistence.GetDomainAuditLogsResponse, err error) {
	op := func() error {
		gp1, err = c.wrapped.GetDomainAuditLogs(ctx, request)
		c.emptyMetric("DomainAuditManager.GetDomainAuditLogs", request, gp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceGetDomainAuditLogsScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredDomainAuditManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}
