// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/metered.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package metered

import (
	"context"

	"github.com/uber/cadence/common/config"
	"github.com/uber/cadence/common/log"
	"github.com/uber/cadence/common/metrics"
	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
)

// meteredSemaphoreMetadataManager implements _sourcePersistence.SemaphoreMetadataManager interface instrumented with rate limiter.
type meteredSemaphoreMetadataManager struct {
	base
	wrapped _sourcePersistence.SemaphoreMetadataManager
}

// NewSemaphoreMetadataManager creates a new instance of SemaphoreMetadataManager with ratelimiter.
func NewSemaphoreMetadataManager(
	wrapped persistence.SemaphoreMetadataManager,
	metricClient metrics.Client,
	logger log.Logger,
	cfg *config.Persistence,
) persistence.SemaphoreMetadataManager {
	return &meteredSemaphoreMetadataManager{
		wrapped: wrapped,
		base: base{
			metricClient:                  metricClient,
			logger:                        logger,
			enableLatencyHistogramMetrics: cfg.EnablePersistenceLatencyHistogramMetrics,
			hostName:                      cfg.HostName,
		},
	}
}

func (c *meteredSemaphoreMetadataManager) Close() {
	c.wrapped.Close()
	return
}

func (c *meteredSemaphoreMetadataManager) CreateSemaphore(ctx context.Context, request *_sourcePersistence.CreateSemaphoreRequest) (cp1 *_sourcePersistence.CreateSemaphoreResponse, err error) {
	op := func() error {
		cp1, err = c.wrapped.CreateSemaphore(ctx, request)
		c.emptyMetric("SemaphoreMetadataManager.CreateSemaphore", request, cp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceCreateSemaphoreScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredSemaphoreMetadataManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *meteredSemaphoreMetadataManager) GetSemaphore(ctx context.Context, request *_sourcePersistence.GetSemaphoreRequest) (gp1 *_sourcePersistence.GetSemaphoreResponse, err error) {
	op := func() error {
		gp1, err = c.wrapped.GetSemaphore(ctx, request)
		c.emptyMetric("SemaphoreMetadataManager.GetSemaphore", request, gp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceGetSemaphoreScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredSemaphoreMetadataManager) ListSemaphores(ctx context.Context, request *_sourcePersistence.ListSemaphoresRequest) (lp1 *_sourcePersistence.ListSemaphoresResponse, err error) {
	op := func() error {
		lp1, err = c.wrapped.ListSemaphores(ctx, request)
		c.emptyMetric("SemaphoreMetadataManager.ListSemaphores", request, lp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceListSemaphoresScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}
