// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/common/archiver (interfaces: HistoryArchiver,VisibilityArchiver)
//
// Generated by this command:
//
//	mockgen -package archiver -destination interface_mock.go github.com/uber/cadence/common/archiver HistoryArchiver,VisibilityArchiver
//

// Package archiver is a generated GoMock package.
package archiver

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHistoryArchiver is a mock of HistoryArchiver interface.
type MockHistoryArchiver struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryArchiverMockRecorder
	isgomock struct{}
}

// MockHistoryArchiverMockRecorder is the mock recorder for MockHistoryArchiver.
type MockHistoryArchiverMockRecorder struct {
	mock *MockHistoryArchiver
}

// NewMockHistoryArchiver creates a new mock instance.
func NewMockHistoryArchiver(ctrl *gomock.Controller) *MockHistoryArchiver {
	mock := &MockHistoryArchiver{ctrl: ctrl}
	mock.recorder = &MockHistoryArchiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryArchiver) EXPECT() *MockHistoryArchiverMockRecorder {
	return m.recorder
}

// Archive mocks base method.
func (m *MockHistoryArchiver) Archive(arg0 context.Context, arg1 URI, arg2 *ArchiveHistoryRequest, arg3 ...ArchiveOption) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Archive", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockHistoryArchiverMockRecorder) Archive(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockHistoryArchiver)(nil).Archive), varargs...)
}

// Get mocks base method.
func (m *MockHistoryArchiver) Get(arg0 context.Context, arg1 URI, arg2 *GetHistoryRequest) (*GetHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*GetHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHistoryArchiverMockRecorder) Get(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHistoryArchiver)(nil).Get), arg0, arg1, arg2)
}

// ValidateURI mocks base method.
func (m *MockHistoryArchiver) ValidateURI(arg0 URI) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateURI", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateURI indicates an expected call of ValidateURI.
func (mr *MockHistoryArchiverMockRecorder) ValidateURI(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateURI", reflect.TypeOf((*MockHistoryArchiver)(nil).ValidateURI), arg0)
}

// MockVisibilityArchiver is a mock of VisibilityArchiver interface.
type MockVisibilityArchiver struct {
	ctrl     *gomock.Controller
	recorder *MockVisibilityArchiverMockRecorder
	isgomock struct{}
}

// MockVisibilityArchiverMockRecorder is the mock recorder for MockVisibilityArchiver.
type MockVisibilityArchiverMockRecorder struct {
	mock *MockVisibilityArchiver
}

// NewMockVisibilityArchiver creates a new mock instance.
func NewMockVisibilityArchiver(ctrl *gomock.Controller) *MockVisibilityArchiver {
	mock := &MockVisibilityArchiver{ctrl: ctrl}
	mock.recorder = &MockVisibilityArchiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVisibilityArchiver) EXPECT() *MockVisibilityArchiverMockRecorder {
	return m.recorder
}

// Archive mocks base method.
func (m *MockVisibilityArchiver) Archive(arg0 context.Context, arg1 URI, arg2 *ArchiveVisibilityRequest, arg3 ...ArchiveOption) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Archive", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockVisibilityArchiverMockRecorder) Archive(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockVisibilityArchiver)(nil).Archive), varargs...)
}

// Query mocks base method.
func (m *MockVisibilityArchiver) Query(arg0 context.Context, arg1 URI, arg2 *QueryVisibilityRequest) (*QueryVisibilityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", arg0, arg1, arg2)
	ret0, _ := ret[0].(*QueryVisibilityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockVisibilityArchiverMockRecorder) Query(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockVisibilityArchiver)(nil).Query), arg0, arg1, arg2)
}

// ValidateURI mocks base method.
func (m *MockVisibilityArchiver) ValidateURI(arg0 URI) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateURI", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateURI indicates an expected call of ValidateURI.
func (mr *MockVisibilityArchiverMockRecorder) ValidateURI(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateURI", reflect.TypeOf((*MockVisibilityArchiver)(nil).ValidateURI), arg0)
}
