// generated by deep-copy -pointer-receiver -o ./data_manager_deepcopy.gen.go -type GetDomainResponse -type ClusterReplicationConfig .; DO NOT EDIT.

package persistence

// DeepCopy generates a deep copy of *GetDomainResponse
func (o *GetDomainResponse) DeepCopy() *GetDomainResponse {
	var cp GetDomainResponse = *o
	if o.Info != nil {
		cp.Info = new(DomainInfo)
		*cp.Info = *o.Info
		if o.Info.Data != nil {
			cp.Info.Data = make(map[string]string, len(o.Info.Data))
			for k4, v4 := range o.Info.Data {
				cp.Info.Data[k4] = v4
			}
		}
	}
	if o.Config != nil {
		cp.Config = new(DomainConfig)
		*cp.Config = *o.Config
		cp.Config.BadBinaries = o.Config.BadBinaries.DeepCopy()
		cp.Config.IsolationGroups = o.Config.IsolationGroups.DeepCopy()
		cp.Config.AsyncWorkflowConfig = o.Config.AsyncWorkflowConfig.DeepCopy()
	}
	if o.ReplicationConfig != nil {
		cp.ReplicationConfig = new(DomainReplicationConfig)
		*cp.ReplicationConfig = *o.ReplicationConfig
		if o.ReplicationConfig.Clusters != nil {
			cp.ReplicationConfig.Clusters = make([]*ClusterReplicationConfig, len(o.ReplicationConfig.Clusters))
			copy(cp.ReplicationConfig.Clusters, o.ReplicationConfig.Clusters)
			for i4 := range o.ReplicationConfig.Clusters {
				if o.ReplicationConfig.Clusters[i4] != nil {
					cp.ReplicationConfig.Clusters[i4] = o.ReplicationConfig.Clusters[i4].DeepCopy()
				}
			}
		}
		if o.ReplicationConfig.ActiveClusters != nil {
			retV := o.ReplicationConfig.ActiveClusters.DeepCopy()
			cp.ReplicationConfig.ActiveClusters = &retV
		}
	}
	if o.FailoverEndTime != nil {
		cp.FailoverEndTime = new(int64)
		*cp.FailoverEndTime = *o.FailoverEndTime
	}
	return &cp
}

// DeepCopy generates a deep copy of *ClusterReplicationConfig
func (o *ClusterReplicationConfig) DeepCopy() *ClusterReplicationConfig {
	var cp ClusterReplicationConfig = *o
	return &cp
}
