{
 "title": "Cadence-Persistence",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "operation",
    "label": "operation",
    "query": {
     "query": "label_values(persistence_requests,operation)"
    }
   },
   {
    "name": "services",
    "label": "services",
    "query": {
     "query": "label_values(cadence_requests,cadence_service)"
    }
   },
   {
    "name": "latency",
    "label": "latency",
    "query": {
     "query": "label_values(cadence_latency_bucket,latency)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Empty Response Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(persistence_empty_response{operation=~\"$operation\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per operation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(persistence_requests{operation=~\"$operation\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Domain",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(domain) (rate(persistence_requests_per_domain[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Domain Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by(domain, operation) (rate(persistence_requests_per_domain[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencies Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "avg by(operation) (rate(persistence_latency_sum{operation=~\"$operation\"}[$__rate_interval]) / rate(persistence_latency_count{operation=~\"$operation\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors Per Operation ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(persistence_errors{operation=~\"$operation\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1- (rate(persistence_errors{operation=~\"$operation\"}[$__rate_interval]) / rate(persistence_requests{operation=~\"$operation\"}[$__rate_interval])))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Requests Per Operation Per Shard",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum by(operation, shard_id) (rate(persistence_requests_per_shard{operation=~\"$operation\"}[$__rate_interval]))",
     "legendFormat": "{{operation}} - {{shard_id}}"
    }
   ]
  },
  {
   "title": "Success Rate Per Operation Per Shard",
   "type": "text",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 44 },
   "options": {
    "content": "# TODO: Persistence errors per shard metric is not defined. Once it's added update this panel"
   }
  }
 ]
}