// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: uber/cadence/sharddistributor/v1/executor.proto

package sharddistributorv1

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// ShardDistributorExecutorAPIYARPCClient is the YARPC client-side interface for the ShardDistributorExecutorAPI service.
type ShardDistributorExecutorAPIYARPCClient interface {
	Heartbeat(context.Context, *HeartbeatRequest, ...yarpc.CallOption) (*HeartbeatResponse, error)
	AssignShard(context.Context, *AssignShardRequest, ...yarpc.CallOption) (*AssignShardResponse, error)
}

func newShardDistributorExecutorAPIYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) ShardDistributorExecutorAPIYARPCClient {
	return &_ShardDistributorExecutorAPIYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.cadence.sharddistributor.v1.ShardDistributorExecutorAPI",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewShardDistributorExecutorAPIYARPCClient builds a new YARPC client for the ShardDistributorExecutorAPI service.
func NewShardDistributorExecutorAPIYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) ShardDistributorExecutorAPIYARPCClient {
	return newShardDistributorExecutorAPIYARPCClient(clientConfig, nil, options...)
}

// ShardDistributorExecutorAPIYARPCServer is the YARPC server-side interface for the ShardDistributorExecutorAPI service.
type ShardDistributorExecutorAPIYARPCServer interface {
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	AssignShard(context.Context, *AssignShardRequest) (*AssignShardResponse, error)
}

type buildShardDistributorExecutorAPIYARPCProceduresParams struct {
	Server      ShardDistributorExecutorAPIYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildShardDistributorExecutorAPIYARPCProcedures(params buildShardDistributorExecutorAPIYARPCProceduresParams) []transport.Procedure {
	handler := &_ShardDistributorExecutorAPIYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName: "uber.cadence.sharddistributor.v1.ShardDistributorExecutorAPI",
			UnaryHandlerParams: []protobuf.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "Heartbeat",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.Heartbeat,
							NewRequest:  newShardDistributorExecutorAPIServiceHeartbeatYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "AssignShard",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.AssignShard,
							NewRequest:  newShardDistributorExecutorAPIServiceAssignShardYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildShardDistributorExecutorAPIYARPCProcedures prepares an implementation of the ShardDistributorExecutorAPI service for YARPC registration.
func BuildShardDistributorExecutorAPIYARPCProcedures(server ShardDistributorExecutorAPIYARPCServer) []transport.Procedure {
	return buildShardDistributorExecutorAPIYARPCProcedures(buildShardDistributorExecutorAPIYARPCProceduresParams{Server: server})
}

// FxShardDistributorExecutorAPIYARPCClientParams defines the input
// for NewFxShardDistributorExecutorAPIYARPCClient. It provides the
// paramaters to get a ShardDistributorExecutorAPIYARPCClient in an
// Fx application.
type FxShardDistributorExecutorAPIYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxShardDistributorExecutorAPIYARPCClientResult defines the output
// of NewFxShardDistributorExecutorAPIYARPCClient. It provides a
// ShardDistributorExecutorAPIYARPCClient to an Fx application.
type FxShardDistributorExecutorAPIYARPCClientResult struct {
	fx.Out

	Client ShardDistributorExecutorAPIYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxShardDistributorExecutorAPIYARPCClient provides a ShardDistributorExecutorAPIYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorExecutorAPIYARPCClient("service-name"),
//	  ...
//	)
func NewFxShardDistributorExecutorAPIYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxShardDistributorExecutorAPIYARPCClientParams) FxShardDistributorExecutorAPIYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxShardDistributorExecutorAPIYARPCClientResult{
			Client: newShardDistributorExecutorAPIYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxShardDistributorExecutorAPIYARPCProceduresParams defines the input
// for NewFxShardDistributorExecutorAPIYARPCProcedures. It provides the
// paramaters to get ShardDistributorExecutorAPIYARPCServer procedures in an
// Fx application.
type FxShardDistributorExecutorAPIYARPCProceduresParams struct {
	fx.In

	Server      ShardDistributorExecutorAPIYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxShardDistributorExecutorAPIYARPCProceduresResult defines the output
// of NewFxShardDistributorExecutorAPIYARPCProcedures. It provides
// ShardDistributorExecutorAPIYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxShardDistributorExecutorAPIYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxShardDistributorExecutorAPIYARPCProcedures provides ShardDistributorExecutorAPIYARPCServer procedures to an Fx application.
// It expects a ShardDistributorExecutorAPIYARPCServer to be present in the container.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorExecutorAPIYARPCProcedures(),
//	  ...
//	)
func NewFxShardDistributorExecutorAPIYARPCProcedures() interface{} {
	return func(params FxShardDistributorExecutorAPIYARPCProceduresParams) FxShardDistributorExecutorAPIYARPCProceduresResult {
		return FxShardDistributorExecutorAPIYARPCProceduresResult{
			Procedures: buildShardDistributorExecutorAPIYARPCProcedures(buildShardDistributorExecutorAPIYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: ShardDistributorExecutorAPIReflectionMeta,
		}
	}
}

// ShardDistributorExecutorAPIReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var ShardDistributorExecutorAPIReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.cadence.sharddistributor.v1.ShardDistributorExecutorAPI",
	FileDescriptors: yarpcFileDescriptorClosure5aab034437d08cca,
}

type _ShardDistributorExecutorAPIYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_ShardDistributorExecutorAPIYARPCCaller) Heartbeat(ctx context.Context, request *HeartbeatRequest, options ...yarpc.CallOption) (*HeartbeatResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Heartbeat", request, newShardDistributorExecutorAPIServiceHeartbeatYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*HeartbeatResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorExecutorAPIServiceHeartbeatYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorExecutorAPIYARPCCaller) AssignShard(ctx context.Context, request *AssignShardRequest, options ...yarpc.CallOption) (*AssignShardResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "AssignShard", request, newShardDistributorExecutorAPIServiceAssignShardYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*AssignShardResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorExecutorAPIServiceAssignShardYARPCResponse, responseMessage)
	}
	return response, err
}

type _ShardDistributorExecutorAPIYARPCHandler struct {
	server ShardDistributorExecutorAPIYARPCServer
}

func (h *_ShardDistributorExecutorAPIYARPCHandler) Heartbeat(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *HeartbeatRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*HeartbeatRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorExecutorAPIServiceHeartbeatYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Heartbeat(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorExecutorAPIYARPCHandler) AssignShard(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *AssignShardRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*AssignShardRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorExecutorAPIServiceAssignShardYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.AssignShard(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newShardDistributorExecutorAPIServiceHeartbeatYARPCRequest() proto.Message {
	return &HeartbeatRequest{}
}

func newShardDistributorExecutorAPIServiceHeartbeatYARPCResponse() proto.Message {
	return &HeartbeatResponse{}
}

func newShardDistributorExecutorAPIServiceAssignShardYARPCRequest() proto.Message {
	return &AssignShardRequest{}
}

func newShardDistributorExecutorAPIServiceAssignShardYARPCResponse() proto.Message {
	return &AssignShardResponse{}
}

var (
	emptyShardDistributorExecutorAPIServiceHeartbeatYARPCRequest    = &HeartbeatRequest{}
	emptyShardDistributorExecutorAPIServiceHeartbeatYARPCResponse   = &HeartbeatResponse{}
	emptyShardDistributorExecutorAPIServiceAssignShardYARPCRequest  = &AssignShardRequest{}
	emptyShardDistributorExecutorAPIServiceAssignShardYARPCResponse = &AssignShardResponse{}
)

var yarpcFileDescriptorClosure5aab034437d08cca = [][]byte{
	// uber/cadence/sharddistributor/v1/executor.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x5d, 0x6f, 0xe2, 0x46,
		0x14, 0xad, 0x4d, 0x92, 0x96, 0x4b, 0x45, 0xcc, 0x34, 0x1f, 0x0e, 0x49, 0x54, 0x8a, 0x54, 0x15,
		0xd1, 0xd6, 0x14, 0xd2, 0x4a, 0x55, 0xfb, 0xe4, 0xc4, 0x16, 0x4c, 0x42, 0x6c, 0x64, 0x9b, 0xb4,
		0xa9, 0x54, 0x59, 0x06, 0x8f, 0x88, 0xd5, 0x60, 0x53, 0xdb, 0xa0, 0x24, 0xda, 0xb7, 0xdd, 0xf7,
		0x7d, 0xda, 0xa7, 0xfd, 0x4f, 0xfb, 0x23, 0xf6, 0x97, 0xac, 0x6c, 0x43, 0xc0, 0x86, 0x08, 0xc8,
		0xae, 0xb4, 0x6f, 0x9e, 0x39, 0xf7, 0x9e, 0x3b, 0x3e, 0xe7, 0x5e, 0x7b, 0xa0, 0x32, 0xec, 0x10,
		0xb7, 0xd2, 0x35, 0x4c, 0x62, 0x77, 0x49, 0xc5, 0xbb, 0x31, 0x5c, 0xd3, 0xb4, 0x3c, 0xdf, 0xb5,
		0x3a, 0x43, 0xdf, 0x71, 0x2b, 0xa3, 0x6a, 0x85, 0xdc, 0x91, 0x6e, 0xf0, 0xcc, 0x0d, 0x5c, 0xc7,
		0x77, 0x50, 0x21, 0x48, 0xe0, 0xc6, 0x09, 0x5c, 0x32, 0x81, 0x1b, 0x55, 0x8b, 0x6f, 0x52, 0xc0,
		0x34, 0x88, 0xe1, 0xfa, 0x1d, 0x62, 0xf8, 0x0a, 0xf9, 0x7f, 0x48, 0x3c, 0x1f, 0x1d, 0x41, 0xda,
		0x36, 0xfa, 0xc4, 0x1b, 0x18, 0x5d, 0xc2, 0x52, 0x05, 0xaa, 0x94, 0x56, 0xa6, 0x1b, 0xe8, 0x5b,
		0xc8, 0x4c, 0xca, 0xe8, 0x96, 0xc9, 0xd2, 0x21, 0x0e, 0x93, 0x2d, 0x6c, 0xa2, 0x06, 0x6c, 0x79,
		0xbe, 0xe1, 0x0f, 0x3d, 0x36, 0x55, 0xa0, 0x4a, 0xd9, 0xda, 0x2f, 0xdc, 0xb2, 0x63, 0x70, 0xe2,
		0x38, 0x5b, 0x0d, 0xf3, 0x94, 0x71, 0x3e, 0x7a, 0x01, 0x3b, 0x61, 0xb4, 0x1e, 0xad, 0x75, 0x97,
		0x0c, 0x1c, 0xd7, 0xf7, 0xd8, 0x8d, 0x42, 0xaa, 0x94, 0xa9, 0x9d, 0x2f, 0xe7, 0x4d, 0xbe, 0x1a,
		0xa7, 0x06, 0x41, 0xe3, 0x2a, 0x11, 0x99, 0x68, 0xfb, 0xee, 0xbd, 0x82, 0xbc, 0x39, 0x20, 0xff,
		0x00, 0xfb, 0x4f, 0x84, 0x23, 0x06, 0x52, 0xff, 0x91, 0xfb, 0xb1, 0x36, 0xc1, 0x23, 0xc2, 0xb0,
		0x39, 0x32, 0x6e, 0x87, 0x24, 0xd4, 0x23, 0x53, 0x3b, 0x59, 0x7e, 0xb6, 0x39, 0x6e, 0x25, 0x62,
		0xf8, 0x83, 0xfe, 0x9d, 0x2a, 0xde, 0x43, 0x6e, 0x0e, 0x47, 0xe2, 0xa3, 0xb0, 0x54, 0x28, 0xec,
		0xcf, 0xeb, 0x15, 0x99, 0xa8, 0x7a, 0x0c, 0x10, 0xa9, 0x7a, 0xeb, 0x18, 0x91, 0x7f, 0x94, 0x92,
		0x0e, 0x77, 0x9a, 0x8e, 0x61, 0x16, 0x5f, 0xd2, 0x90, 0x9b, 0xd1, 0xcd, 0x1b, 0x38, 0xb6, 0x47,
		0xd0, 0x08, 0x72, 0x51, 0x92, 0xe1, 0x79, 0x56, 0xcf, 0xee, 0x13, 0xdb, 0x0f, 0x8e, 0x11, 0xf8,
		0x80, 0xd7, 0xf2, 0x21, 0xe2, 0x8b, 0x0e, 0xc6, 0x4f, 0xb9, 0x22, 0x1b, 0x18, 0x2f, 0xb1, 0x9d,
		0x1f, 0xc1, 0xee, 0xc2, 0xd0, 0x05, 0x16, 0xd4, 0xe3, 0x16, 0x54, 0x57, 0x54, 0x67, 0xca, 0x3c,
		0x6b, 0xc0, 0xbf, 0xb0, 0x9d, 0x40, 0xd1, 0x79, 0x42, 0xfe, 0xda, 0xf2, 0x02, 0xd3, 0xec, 0xb8,
		0x07, 0xc5, 0xb7, 0x34, 0xa0, 0x08, 0x0c, 0xab, 0x7c, 0xa2, 0xc9, 0xbb, 0x86, 0xed, 0xc7, 0x80,
		0x8f, 0x1c, 0xc1, 0x2c, 0x89, 0xad, 0xd1, 0x01, 0x7c, 0x15, 0xf9, 0x6f, 0x99, 0xec, 0x46, 0x58,
		0xf8, 0xcb, 0x70, 0x8d, 0x4d, 0xd4, 0x82, 0xaf, 0x67, 0xa7, 0x94, 0xdd, 0x7c, 0x4e, 0x73, 0x66,
		0x66, 0x06, 0xb0, 0xf8, 0x9e, 0x86, 0x6f, 0x62, 0xea, 0x8c, 0x9b, 0xf0, 0xee, 0xe9, 0x26, 0xbc,
		0x58, 0xd5, 0x8c, 0x18, 0xe3, 0xaa, 0x6d, 0x18, 0x28, 0xdb, 0xb7, 0x7a, 0xae, 0xe1, 0x5b, 0x8e,
		0xad, 0x0f, 0x6e, 0x0c, 0x2f, 0xea, 0xb2, 0x95, 0x94, 0xbd, 0x9c, 0x24, 0xb6, 0x82, 0x3c, 0x25,
		0xdb, 0x8f, 0xad, 0x3f, 0x57, 0x87, 0x97, 0x5f, 0x51, 0x90, 0x8d, 0x9b, 0x8e, 0x0e, 0x61, 0x5f,
		0xfc, 0x5b, 0x3c, 0x6b, 0x6b, 0xb2, 0xa2, 0xab, 0x1a, 0xaf, 0xb5, 0x55, 0x1d, 0x4b, 0x57, 0x7c,
		0x13, 0x0b, 0xcc, 0x17, 0x28, 0x0f, 0x7b, 0x49, 0x90, 0x3f, 0xd3, 0xf0, 0x95, 0xc8, 0x50, 0xe8,
		0x08, 0xd8, 0x24, 0x26, 0x28, 0x3c, 0x96, 0xb0, 0x54, 0x67, 0xe8, 0x45, 0xb4, 0x21, 0x2a, 0x0a,
		0x4c, 0xaa, 0x7c, 0x05, 0x99, 0x99, 0x3e, 0x40, 0x2c, 0xec, 0xa8, 0x0d, 0x5e, 0x11, 0xe6, 0xeb,
		0xef, 0x01, 0x8a, 0x21, 0x8a, 0xc8, 0x0b, 0xd7, 0x0c, 0x85, 0x76, 0x21, 0x17, 0xdb, 0x17, 0x64,
		0x49, 0x64, 0xe8, 0xb2, 0x04, 0x4c, 0x72, 0xfa, 0xd0, 0x31, 0x1c, 0xf0, 0xaa, 0x8a, 0xeb, 0xd2,
		0xa5, 0x28, 0x69, 0xf3, 0x15, 0x0e, 0x61, 0x7f, 0x1e, 0x1e, 0x97, 0x29, 0xbf, 0xa3, 0x20, 0x1b,
		0x77, 0x32, 0x88, 0xbf, 0xc4, 0x75, 0x85, 0xd7, 0xb0, 0x2c, 0xe9, 0xad, 0x06, 0xaf, 0x8a, 0x33,
		0x64, 0xdf, 0xc3, 0x77, 0x49, 0xb0, 0x29, 0x9f, 0xf1, 0x4d, 0xbd, 0xc5, 0xab, 0xaa, 0xd6, 0x50,
		0xe4, 0x76, 0xbd, 0xc1, 0x50, 0xe8, 0x27, 0x28, 0x2d, 0x0d, 0xd3, 0xd5, 0x06, 0x2f, 0xc8, 0x7f,
		0x31, 0x34, 0xfa, 0x11, 0x7e, 0x48, 0x46, 0x0b, 0x58, 0xd5, 0x14, 0x7c, 0xda, 0xd6, 0x44, 0x21,
		0x46, 0x9d, 0x0a, 0xde, 0x36, 0x19, 0x2c, 0x4b, 0xa7, 0x32, 0xaf, 0x08, 0xa2, 0xc0, 0x6c, 0xd4,
		0x5e, 0xd3, 0x70, 0x18, 0x2a, 0x2f, 0x4c, 0x5b, 0x66, 0xd2, 0x0f, 0x7c, 0x0b, 0x23, 0x1f, 0xd2,
		0x8f, 0x9f, 0x6d, 0x54, 0x5b, 0xff, 0x5f, 0x9b, 0x3f, 0x79, 0xc6, 0x7f, 0x01, 0x3d, 0x40, 0x66,
		0x66, 0x4e, 0xd1, 0xaf, 0x6b, 0x8e, 0x75, 0x54, 0xf9, 0xb7, 0x67, 0x7d, 0x0c, 0x4e, 0x2f, 0xfe,
		0xc1, 0x3d, 0xcb, 0xbf, 0x19, 0x76, 0xb8, 0xae, 0xd3, 0x8f, 0x5f, 0xb6, 0xb8, 0x1e, 0xb1, 0x2b,
		0xe1, 0xa5, 0x6a, 0xd1, 0xbd, 0xeb, 0xcf, 0xe4, 0xde, 0xa8, 0xda, 0xd9, 0x0a, 0xa3, 0x4f, 0x3e,
		0x04, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x20, 0xaa, 0xaa, 0xb5, 0x09, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) ShardDistributorExecutorAPIYARPCClient {
			return NewShardDistributorExecutorAPIYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
