{
 "title": "Cadence Worker",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "services",
    "label": "services",
    "query": {
     "query": "label_values(cadence_requests,cadence_service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Replication Task Generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tasks Requests Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(task_requests{cadence_service=\"cadence_history\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Generation Latency Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(task_latency_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Task Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Parallel Task Submit Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(paralleltask_submit_request{cadence_service=\"cadence_history\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Tasks Count Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(replication_tasks_count_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Tasks Count Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(replication_tasks_count_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "History Event Notification",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(history_event_notification_inflight_message_gauge{cadence_service=\"cadence_history\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HistoryEventNotification Fanout Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(history_event_notification_fanout_latency_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HistoryEventNotification Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(history_event_notification_queueing_latency_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Latency Per Domain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, domain) (rate(task_latency_queue_per_domain_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go GC detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Total allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by(cadence_service) (rate(memory_allocated{cadence_service=\"$services\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Num",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by(cadence_service) (rate(memory_num_gc{cadence_service=\"$services\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by(cadence_service) (rate(num_goroutines{cadence_service=\"$services\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap in Use (HeapAlloc)",
   "type": "timeseries",
   "description": "HeapInuse is bytes in in-use spans.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum by(cadence_service) (rate(memory_heapinuse{cadence_service=\"$services\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Available (HeapIdle)",
   "type": "timeseries",
   "description": "HeapIdle is bytes in idle (unused) spans.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum by(cadence_service) (rate(memory_heapidle{cadence_service=\"$services\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stack In use",
   "type": "timeseries",
   "description": "Bytes of stack memory obtained from the OS. Plus any memory obtained directly from the OS for OS thread stacks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum by(cadence_service) (rate(memory_stack{cadence_service=\"$services\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}