{
 "title": "Cadence-Archival",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values(activity_end_to_end_latency_sum,domain)"
    }
   },
   { "name": "quantiles", "label": "Quantiles", "query": "0.5, 0.95, 0.99" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Archivals Triggered Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(cadence_service) (changes(archiver_client_history_request{operation=\"ArchiverClient\"}[$__interval]))",
     "legendFormat": "history"
    },
    {
     "expr": "sum by(cadence_service) (rate(archiver_client_visibility_request{operation=\"ArchiverClient\"}[$__rate_interval]))",
     "legendFormat": "visibility"
    }
   ]
  },
  {
   "title": "Client Requests vs Inline Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(cadence_service) (changes(archiver_client_history_request{operation=\"ArchiverClient\"}[$__interval]))",
     "legendFormat": "archiver_client_history_request"
    },
    {
     "expr": "sum by(cadence_service) (changes(archiver_client_history_inline_archive_attempt{operation=\"ArchiverClient\"}[$__interval]))",
     "legendFormat": "archiver_client_history_inline_archive_attempt"
    },
    {
     "expr": "sum by(__name__) (rate(archiver_client_visibility_request{operation=\"ArchiverClient\"}[$__rate_interval]))",
     "legendFormat": "archiver_client_visibility_request"
    },
    {
     "expr": "sum by(__name__) (rate(archiver_client_visibility_inline_archive_attempt{operation=\"ArchiverClient\"}[$__rate_interval]))",
     "legendFormat": "archiver_client_visibility_inline_archive_attempt"
    }
   ]
  },
  {
   "title": "Archiver History Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(archiver_client_history_request{operation=\"ArchiverClient\"}[$__rate_interval]))",
     "legendFormat": "archiver_client_history_request"
    }
   ]
  },
  {
   "title": "Client History Inline Attemptss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(__name__) (rate(archiver_client_history_inline_archive_attempt{operation=\"ArchiverClient\"}[$__rate_interval]))",
     "legendFormat": "archiver_client_history_inline_archive_attempt"
    }
   ]
  },
  {
   "title": "History Requests Per Domain Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(domain, operation) (rate(archiver_client_history_request_per_domain{domain=\"$domain\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "History Inline Attempt Per Domain Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(domain, operation) (rate(archiver_client_history_inline_archive_attempt_per_domain[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Cleanup Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(workflow_cleanup_archive[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "History Inline Attempt Per Domain Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {}
   ]
  }
 ]
}