{
 "title": "Cadence-History",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values(activity_end_to_end_latency_bucket,domain)"
    }
   },
   {
    "name": "services",
    "label": "services",
    "query": {
     "query": "label_values(cadence_requests,cadence_service)"
    }
   },
   { "name": "latency", "label": "latency", "query": "p99,upper,mean,median,lower" }
  ]
 },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Per API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(operation) (rate(cadence_requests{cadence_service=\"cadence_history\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "History API p99 Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(cadence_latency_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Decisions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Decision Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 505 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(complete_workflow_decision{operation=\"RespondDecisionTaskCompleted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (rate(schedule_activity_decision{operation=\"RespondDecisionTaskCompleted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (rate(fail_workflow_decision{operation=\"RespondDecisionTaskCompleted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (rate(cancel_workflow_decision{operation=\"RespondDecisionTaskCompleted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (rate(start_timer_decision{operation=\"RespondDecisionTaskCompleted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (rate(cancel_activity_decision{operation=\"RespondDecisionTaskCompleted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (rate(cancel_timer_decision{operation=\"RespondDecisionTaskCompleted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (rate(cancel_activity_decision{operation=\"RespondDecisionTaskCompleted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (rate(record_marker_decision{operation=\"RespondDecisionTaskCompleted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (rate(cancel_external_workflow_decision{operation=\"RespondDecisionTaskCompleted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (rate(continue_as_new_decision{operation=\"RespondDecisionTaskCompleted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (rate(child_workflow_decision{operation=\"RespondDecisionTaskCompleted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bad Decisions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 505 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(multiple_completion_decisions{operation=\"RespondDecisionTaskCompleted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (rate(failed_decisions{operation=\"RespondDecisionTaskCompleted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "History Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "History Clients Requests Vs Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 505 },
     "targets": [
      {
       "expr": "sum by(cadence_service) (rate(cadence_client_requests{cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "{{cadence_service}} (request)"
      },
      {
       "expr": "sum by(cadence_service) (changes(cadence_client_errors{cadence_service=\"cadence_history\"}[$__interval]))",
       "legendFormat": "{{cadence_service}} (error)"
      }
     ]
    },
    {
     "title": "History Clients Request Count Per API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 505 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_client_requests{cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(operation) (changes(cadence_client_errors{cadence_service=\"cadence_history\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "History Client Error Counts Per API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 513 },
     "targets": [
      {
       "expr": "sum by(operation) (changes(cadence_client_errors{cadence_service=\"cadence_history\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "History Clients API Latencies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 513 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(cadence_client_latency_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "History Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mutable State Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 505 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cache_requests{cache_type=\"mutablestate\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "{{operation}} (request)"
      },
      {
       "expr": "sum by(operation) (rate(cache_miss{cadence_service=\"cadence_history\", cache_type=\"mutablestate\"}[$__rate_interval]))",
       "legendFormat": "{{operation}} (miss)"
      }
     ]
    },
    {
     "title": "Mutable State Cache Latencies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 505 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(cache_latency_bucket{cache_type=\"mutablestate\", cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Events Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 513 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cache_requests{cache_type=\"events\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "{{operation}} (request)"
      },
      {
       "expr": "sum by(operation) (rate(cache_miss{cadence_service=\"cadence_history\", cache_type=\"events\"}[$__rate_interval]))",
       "legendFormat": "{{operation}} (miss)"
      }
     ]
    },
    {
     "title": "Events Cache Latencies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 513 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(cache_latency_bucket{cache_type=\"mutablestate\", cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Execution Lock Held Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 521 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, max by(le, operation) (rate(workflow_context_lock_latency_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ShardController",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shard Movement",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(acquire_shards_count{cadence_service=\"cadence_history\", operation=\"ShardController\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "p99 Latencies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(get_engine_for_shard_latency_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "{{operation}} (get_engine)"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(persistence_latency_per_shard_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "{{operation}} (persistence_latency_per_shard)"
      }
     ]
    },
    {
     "title": "Replication / Transfer p99 Lag (buggy)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 457 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(shardinfo_transfer_lag_count{cadence_service=\"cadence_history\", operation=\"ShardInfo\"}[$__rate_interval]))",
       "legendFormat": "{{operation}} (shard info transfer)"
      },
      {
       "expr": "sum by(operation) (rate(shardinfo_replication_lag_count{cadence_service=\"cadence_history\", operation=\"ShardInfo\"}[$__rate_interval]))",
       "legendFormat": "{{operation}} (shard info replication)"
      }
     ]
    },
    {
     "title": "Timer p99 Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 457 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(shardinfo_timer_lag_bucket{operation=\"ShardInfo\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transfer Level p99 Diff",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 465 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(shardinfo_transfer_diff_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Timer Level p99 Diff",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 465 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(shardinfo_timer_diff_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failover p99 In Progress",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 473 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(shardinfo_transfer_failover_in_progress_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "{{operation}} (transfer failover)"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(shardinfo_timer_failover_in_progress_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "{{operation}} (timer failover)"
      }
     ]
    },
    {
     "title": "Pending p99 Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 473 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(shardinfo_transfer_active_pending_task_bucket[$__rate_interval])))",
       "legendFormat": "{{operation}} (transfer active pending task)"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(shardinfo_timer_active_pending_task_bucket[$__rate_interval])))",
       "legendFormat": "{{operation}} (timer active pending task)"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests vs Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum by(__name__) (rate(persistence_requests{cadence_service=\"cadence_matching\"}[$__rate_interval]))",
       "legendFormat": "persistence_requests"
      },
      {
       "expr": "rate(persistence_errors_entity_not_exists{cadence_service=\"cadence_history\"}[$__rate_interval])",
       "legendFormat": "persistence_errors"
      }
     ]
    },
    {
     "title": "Error Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "rate(persistence_errors_entity_not_exists{cadence_service=\"cadence_history\"}[$__rate_interval])",
       "legendFormat": "EntityNotExists"
      }
     ]
    },
    {
     "title": "Requests Per Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(persistence_requests{cadence_service=\"cadence_matching\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Per Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(persistence_errors_entity_not_exists{cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Operation p99 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
     "targets": [
      {
       "expr": "avg by(operation) (rate(persistence_latency_bucket{cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Timer Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Ack Level Update",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(ack_level_update{cadence_service=\"cadence_history\", operation=\"TimerActiveQueueProcessor\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Standby Ack Level Update",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(ack_level_update{cadence_service=\"cadence_history\", operation=\"TimerStandByQueueProcessor\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Timer Notifications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(new_timer_notifications{operation=\"TimerActiveQueueProcessor\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Standby New Timer Notifications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "rate(new_timer_notifications{operation=\"TimerStandByQueueProcessor\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Timer Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(task_requests{operation=\"TimerActiveTaskActivityTimeout\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Timer Processing p99 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(task_latency_processing_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Timer p99 Attempt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(task_attempt_bucket{operation=~\"TimerActiveTaskActivityTimeout|TimerActiveTaskDecisionTimeout|TimerActiveTaskWorkflowTimeout\", cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Timer Queue p99 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(task_latency_queue_bucket{operation=~\"TimerActiveTaskActivityTimeout|TimerActiveTaskDecisionTimeout|TimerActiveTaskWorkflowTimeout\", cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Transfer Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Ack Level Update",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(ack_level_update{cadence_service=\"cadence_history\", operation=\"TransferActiveQueueProcessor\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Standby Ack Level Update",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(ack_level_update{cadence_service=\"cadence_history\", operation=\"TransferStandByQueueProcessor\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Timer Notifications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(new_timer_notifications{operation=\"TransferActiveQueueProcessor\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Standby New Timer Notifications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "rate(new_timer_notifications{operation=\"TranferStandByQueueProcessor\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Timer Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(task_requests{operation=\"TransferActiveTaskActivityTimeout\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Timer Processing p99 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(task_latency_processing_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Timer p99 Attempt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(task_attempt_bucket{operation=~\"TransferActiveTaskActivityTimeout|TransferActiveTaskDecisionTimeout|TransferActiveTaskWorkflowTimeout\", cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Timer Queue p99 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(task_latency_queue_bucket{operation=~\"TransferActiveTaskActivityTimeout|TransferActiveTaskDecisionTimeout|TransferActiveTaskWorkflowTimeout\", cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}