{
 "title": "Cadence-Server",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values(activity_end_to_end_latency_sum,domain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top Domains for Regular Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(domain) (cadence_requests{cadence_service=\"cadence_frontend\", operation=~\"SignalWithStartWorkflowExecution|SignalWorkflowxecution|StartWorkflowExecution|TerminateWorkflowExecution|ResetWorkflowExecution|RequestCancelWorkflowexecution|ListWorkflowExecutions\"})",
     "legendFormat": "{{domain}}"
    },
    {}
   ]
  },
  {
   "title": "Top Domains for Workflow Worker Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(domain) (cadence_requests{cadence_service=\"cadence_frontend\", operation=~\"PollForDecisionTask|GetWorkflowExecutionHistory|RespondDecisionTaskCompleted\"})",
     "legendFormat": "{{domain}}{{operation}}"
    }
   ]
  },
  {
   "title": "Top Domains for All Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(domain) (cadence_requests{cadence_service=\"cadence_frontend\"})",
     "legendFormat": "{{domain}}{{operation}}"
    }
   ]
  },
  {
   "title": "Top Domains for Activity Worker Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cadence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\", operation=~\"PollForActivityTask|RespondActivityTaskCompleted\"}) by (domain)",
     "legendFormat": "{{domain}}{{operation}}"
    }
   ]
  },
  {
   "title": "All API per second per domain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(domain) (rate(cadence_requests{cadence_service=\"cadence_frontend\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API per second(breakdown per operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(operation) (rate(cadence_requests{cadence_service=\"cadence_frontend\", domain=\"$domain\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Regular API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, operation) (rate(cadence_latency_bucket{operation!~\"CountWorkflowExecutions|GetWorkflowExecutionHistory|ListClosedWorkflowExecutions|ListOpenWorkflowExecutions|ListWorkflowExecutions|PollForActivityTask|PollForDecisionTask|QueryWorkflow\", cadence_service=\"cadence_frontend\"}[$__rate_interval])))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "ListWorkflow API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, operation) (rate(cadence_latency_bucket{operation=~\"CountWorkflowExecutions|GetWorkflowExecutionHistory|ListClosedWorkflowExecutions|ListOpenWorkflowExecutions|ListWorkflowExecutions|PollForActivityTask|PollForDecisionTask|QueryWorkflow\", cadence_service=\"cadence_frontend\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Long Poll API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, operation) (rate(cadence_latency_bucket{operation=\"PollForDecisionTask\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, operation) (rate(cadence_latency_bucket{operation=\"PollForActivityTask\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Regular API Per Domain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(domain, operation) (cadence_requests{cadence_service=\"cadence_frontend\", operation!~\"CountWorkflowExecutions|GetWorkflowExecutionHistory|ListClosedWorkflowExecutions|ListOpenWorkflowExecutions|ListWorkflowExecutions|PollForActivityTask|PollForDecisionTask|QueryWorkflow\"})",
     "legendFormat": "Domain: {{domain}}- Operation: {{operation}}"
    }
   ]
  },
  {
   "title": "API  errors per second(breakdown per operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(operation) (rate(cadence_errors{cadence_service=\"cadence_frontend\", domain=\"$domain\"}[$__rate_interval]))",
     "legendFormat": "Internal server error"
    },
    {
     "expr": "sum(rate(cadence_errors_bad_request{cadence_service=\"cadence_frontend\"}[2m]))",
     "legendFormat": "Bad Requests error"
    },
    {
     "expr": "sum(rate(cadence_errors_query_failed{cadence_service=\"cadence_frontend\"}[2m]))",
     "legendFormat": "QueryFailed error"
    },
    {
     "expr": "sum(rate(cadence_errors_context_timeout{cadence_service=\"cadence_frontend\"}[2m]))",
     "legendFormat": "ContextTimeout error"
    },
    {
     "expr": "sum(rate(cadence_errors_entity_not_exists{cadence_service=\"cadence_frontend\"}[2m]))",
     "legendFormat": "EntityNotExists error"
    },
    {
     "expr": "sum(rate(cadence_errors_execution_already_started{cadence_service=\"cadence_frontend\"}[2m]))",
     "legendFormat": "WorkflowAlreadyStarted error"
    },
    {
     "expr": "sum(rate(cadence_errors_workflow_execution_already_completed{cadence_service=\"cadence_frontend\"}[2m]))",
     "legendFormat": "WorkflowAlreadyCompleted"
    }
   ]
  },
  {
   "title": "GetHistory/QueryWorkflow API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, operation) (rate(cadence_latency_bucket{cadence_service=\"cadence_frontend\", operation=~\"GetWorkflowExecutionHistory|QueryWorkflow\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WorkflowClient API per seconds by domain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(domain, operation) (changes(cadence_requests{cadence_service=\"cadence_frontend\", operation=~\"SignalWithStartworkflowExecution|SignalWorkflowExecution|StartWorkflowExecution|TerminateWorkflowExecution|ResetWorkflowExecution|RequestCancelWorkflowExecution|ListWorkflowExecutions\", domain=\"$domain\"}[$__interval]))",
     "legendFormat": "Domain: {{domain}}- Operation: {{operation}}"
    }
   ]
  },
  {
   "title": "Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 641 },
     "targets": [
      {
       "expr": "sum by(cadence_service) (rate(restarts[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Shard Movements per sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 641 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(acquire_shards_count[$__rate_interval]))",
       "legendFormat": "{{operation}} (shard acquire count)"
      },
      {
       "expr": "sum by(__name__) (rate(sharditem_created_count[$__rate_interval]))",
       "legendFormat": "shard item created count"
      },
      {
       "expr": "sum by(__name__) (changes(numshards_gauge[$__interval]))",
       "legendFormat": "num of shard gauge"
      },
      {
       "expr": "sum by(__name__) (changes(persistence_requests_per_shard[$__interval]))",
       "legendFormat": "persistence requests per shard"
      }
     ]
    },
    {
     "title": "Goroutines (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1537 },
     "targets": [
      {
       "expr": "avg by(cadence_service) (num_goroutines)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Rates per second",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "External Events per sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1618 },
     "targets": [
      {
       "expr": "sum by(operation) (changes(cadence_requests{cadence_service=\"cadence_history\", operation=~\"StartWorkflowExecution|SignalWorkflowExecution\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Activities per sec ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1618 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{operation=~\"RespondActivityTaskCompleted|RecordActivityTaskHeartbeat|RecordActivityTaskStarted|RespondDecisionTaskCompleted\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Polls per sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1626 },
     "targets": [
      {
       "expr": "sum by(operation) (changes(cadence_requests{operation=~\"PollForActivityTask|PollForDecisionTask|CancelOutstandingPoll\"}[$__interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(__name__) (changes(poll_success_sync{cadence_service=\"cadence_matching\"}[$__interval]))",
       "legendFormat": "poll success sync"
      },
      {
       "expr": "sum by(__name__) (rate(poll_timeouts{cadence_service=\"cadence_matching\"}[$__rate_interval]))",
       "legendFormat": "poll timeout"
      }
     ]
    },
    {
     "title": "Decisions per sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1626 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(cadence_requests{operation=~\"RecordDecisionTaskStarted|RespondDecisionTaskCompleted\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Version Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend Versions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 643 },
     "targets": [
      {
       "expr": "sum by(cadence_version) (build_information{cadence_service=\"cadence_frontend\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "History Versions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 643 },
     "targets": [
      {
       "expr": "sum by(cadence_version) (build_information{cadence_service=\"cadence_history\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Worker Versions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 643 },
     "targets": [
      {
       "expr": "sum by(cadence_version) (build_information{cadence_service=\"cadence_worker\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Matching Versions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 643 },
     "targets": [
      {
       "expr": "sum by(cadence_version) (build_information{cadence_service=\"cadence_matching\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Timer Task Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timer Tasks Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 644 },
     "targets": [
      {
       "expr": "sum by(operation) (changes(task_requests{cadence_service=\"cadence_history\", operation=~\"TimerActiveTaskActivityTimeout|TimerActiveTaskDecisionTimeout|TimerActiveTaskWorkflowTimeout\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Timer Task Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 644 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (task_latency_bucket{operation=~\"TimerActiveTaskActivityTimeout|TimerActiveTaskDecisionTimeout|TimerActiveTaskWorkflowTimeout\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Timer Tasks Per Domain per sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1108 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(domain) (changes(task_requests_per_domain{operation=~\"TimerActiveTaskActivityTimeout|TimerActiveTaskDecisionTimeout|TimerActiveTaskWorkflowTimeout\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Timer Task Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1108 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, domain) (rate(task_latency_per_domain_bucket{operation=~\"TimerActiveTaskActivityTimeout|TimerActiveTaskDecisionTimeout|TimerActiveTaskWorkflowTimeout\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Transfer Task Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transfer Tasks Requests Vs Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 645 },
     "targets": [
      {
       "expr": "sum by(__name__) (rate(task_requests{operation=~\"TransferActiveTaskCloseExecution|TransferActiveTaskDecision|TransferActiveTaskRecordWorkflowStarted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum by(__name__) (rate(task_errors{operation=~\"TransferActiveTaskCloseExecution|TransferActiveTaskDecision|TransferActiveTaskRecordWorkflowStarted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Transfer Tasks Requests Per Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 797 },
     "targets": [
      {
       "expr": "sum by(operation) (rate(task_requests{operation=~\"TransferActiveTaskCloseExecution|TransferActiveTaskDecision|TransferActiveTaskRecordWorkflowStarted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transfer Task Latency (upper)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 797 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, operation) (rate(task_latency_bucket{operation=~\"TransferActiveTaskCloseExecution|TransferActiveTaskDecision|TransferActiveTaskRecordWorkflowStarted\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transfer Tasks Per Domain (Top 20)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 805 },
     "targets": [
      {
       "expr": "sum by(domain) (rate(task_requests_per_domain{operation=~\"TransferActiveTaskCloseExecution|TransferActiveTaskDecision|TransferActiveTaskRecordWorkflowStarted\", cadence_service=\"cadence_history\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transfer Task upper Latency per Domain (Top 20)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 805 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, domain) (rate(task_latency_per_domain_bucket{operation=~\"TransferActiveTaskCloseExecution|TransferActiveTaskDecision|TransferActiveTaskRecordWorkflowStarted\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Size and Count Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "History Size By Domain (Top 20)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 641 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, domain) (rate(history_size_bucket{operation=\"ExecutionStats\", cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "History Event Count By Domain",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 641 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, domain) (rate(history_count_bucket{operation=~\"ExecutionStats\", cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Frontend Blob Sizes Top Domains",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1105 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, max by(le, domain) (rate(event_blob_size_bucket{cadence_service=\"cadence_frontend\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Frontend Blob Sizes Top Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1105 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, max by(le, operation) (rate(event_blob_size_bucket{cadence_service=\"cadence_frontend\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Decision Blob Sizes by Domain",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1113 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, max by(le, domain) (rate(event_blob_size_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Decision Blob Sizes by DecisionType",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1113 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, max by(le, decisionType) (rate(event_blob_size_bucket{cadence_service=\"cadence_history\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Decision Result Count Top Domains",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1121 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, max by(le, domain) (rate(decision_result_count_bucket{cadence_service=\"cadence_frontend\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}