// generated by deep-copy -o ./admin_deepcopy.gen.go -type AsyncWorkflowConfiguration .; DO NOT EDIT.

package types

// DeepCopy generates a deep copy of AsyncWorkflowConfiguration
func (o AsyncWorkflowConfiguration) DeepCopy() AsyncWorkflowConfiguration {
	var cp AsyncWorkflowConfiguration = o
	if o.QueueConfig != nil {
		cp.QueueConfig = o.QueueConfig.DeepCopy()
	}
	return cp
}
