// Code generated by "enumer -type=LoadBalancingMode -trimprefix=LoadBalancingMode -json -output sharddistributor_load_balancing_mode_enumer_generated.go"; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _LoadBalancingModeName = "INVALIDNAIVEGREEDY"

var _LoadBalancingModeIndex = [...]uint8{0, 7, 12, 18}

const _LoadBalancingModeLowerName = "invalidnaivegreedy"

func (i LoadBalancingMode) String() string {
	if i < 0 || i >= LoadBalancingMode(len(_LoadBalancingModeIndex)-1) {
		return fmt.Sprintf("LoadBalancingMode(%d)", i)
	}
	return _LoadBalancingModeName[_LoadBalancingModeIndex[i]:_LoadBalancingModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LoadBalancingModeNoOp() {
	var x [1]struct{}
	_ = x[LoadBalancingModeINVALID-(0)]
	_ = x[LoadBalancingModeNAIVE-(1)]
	_ = x[LoadBalancingModeGREEDY-(2)]
}

var _LoadBalancingModeValues = []LoadBalancingMode{LoadBalancingModeINVALID, LoadBalancingModeNAIVE, LoadBalancingModeGREEDY}

var _LoadBalancingModeNameToValueMap = map[string]LoadBalancingMode{
	_LoadBalancingModeName[0:7]:        LoadBalancingModeINVALID,
	_LoadBalancingModeLowerName[0:7]:   LoadBalancingModeINVALID,
	_LoadBalancingModeName[7:12]:       LoadBalancingModeNAIVE,
	_LoadBalancingModeLowerName[7:12]:  LoadBalancingModeNAIVE,
	_LoadBalancingModeName[12:18]:      LoadBalancingModeGREEDY,
	_LoadBalancingModeLowerName[12:18]: LoadBalancingModeGREEDY,
}

var _LoadBalancingModeNames = []string{
	_LoadBalancingModeName[0:7],
	_LoadBalancingModeName[7:12],
	_LoadBalancingModeName[12:18],
}

// LoadBalancingModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LoadBalancingModeString(s string) (LoadBalancingMode, error) {
	if val, ok := _LoadBalancingModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LoadBalancingModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LoadBalancingMode values", s)
}

// LoadBalancingModeValues returns all values of the enum
func LoadBalancingModeValues() []LoadBalancingMode {
	return _LoadBalancingModeValues
}

// LoadBalancingModeStrings returns a slice of all String values of the enum
func LoadBalancingModeStrings() []string {
	strs := make([]string, len(_LoadBalancingModeNames))
	copy(strs, _LoadBalancingModeNames)
	return strs
}

// IsALoadBalancingMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LoadBalancingMode) IsALoadBalancingMode() bool {
	for _, v := range _LoadBalancingModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for LoadBalancingMode
func (i LoadBalancingMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for LoadBalancingMode
func (i *LoadBalancingMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("LoadBalancingMode should be a string, got %s", data)
	}

	var err error
	*i, err = LoadBalancingModeString(s)
	return err
}
