// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/errorinjector.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package errorinjectors

import (
	"context"
	"time"

	"github.com/uber/cadence/common/log"
	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
)

// injectorAsyncWorkflowQueueManager implements _sourcePersistence.AsyncWorkflowQueueManager interface instrumented with error injection.
type injectorAsyncWorkflowQueueManager struct {
	wrapped   _sourcePersistence.AsyncWorkflowQueueManager
	starttime time.Time
	errorRate float64
	logger    log.Logger
}

// NewAsyncWorkflowQueueManager creates a new instance of AsyncWorkflowQueueManager with error injection.
func NewAsyncWorkflowQueueManager(
	wrapped persistence.AsyncWorkflowQueueManager,
	errorRate float64,
	logger log.Logger,
	starttime time.Time,
) persistence.AsyncWorkflowQueueManager {
	return &injectorAsyncWorkflowQueueManager{
		wrapped:   wrapped,
		starttime: starttime,
		errorRate: errorRate,
		logger:    logger,
	}
}

func (c *injectorAsyncWorkflowQueueManager) Close() {
	c.wrapped.Close()
	return
}

func (c *injectorAsyncWorkflowQueueManager) EnqueueAsyncWorkflowMessage(ctx context.Context, request *_sourcePersistence.EnqueueAsyncWorkflowMessageRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.EnqueueAsyncWorkflowMessage(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.EnqueueAsyncWorkflowMessage", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorAsyncWorkflowQueueManager) EnqueueAsyncWorkflowMessageToDLQ(ctx context.Context, request *_sourcePersistence.EnqueueAsyncWorkflowMessageToDLQRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.EnqueueAsyncWorkflowMessageToDLQ(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.EnqueueAsyncWorkflowMessageToDLQ", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorAsyncWorkflowQueueManager) GetAsyncWorkflowAckLevels(ctx context.Context, request *_sourcePersistence.GetAsyncWorkflowAckLevelsRequest) (gp1 *_sourcePersistence.GetAsyncWorkflowAckLevelsResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		gp1, err = c.wrapped.GetAsyncWorkflowAckLevels(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.GetAsyncWorkflowAckLevels", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorAsyncWorkflowQueueManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *injectorAsyncWorkflowQueueManager) RangeDeleteAsyncWorkflowMessages(ctx context.Context, request *_sourcePersistence.RangeDeleteAsyncWorkflowMessagesRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.RangeDeleteAsyncWorkflowMessages(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.RangeDeleteAsyncWorkflowMessages", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorAsyncWorkflowQueueManager) RangeDeleteAsyncWorkflowMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.RangeDeleteAsyncWorkflowMessagesFromDLQRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.RangeDeleteAsyncWorkflowMessagesFromDLQ(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.RangeDeleteAsyncWorkflowMessagesFromDLQ", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorAsyncWorkflowQueueManager) ReadAsyncWorkflowMessages(ctx context.Context, request *_sourcePersistence.ReadAsyncWorkflowMessagesRequest) (rp1 *_sourcePersistence.ReadAsyncWorkflowMessagesResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		rp1, err = c.wrapped.ReadAsyncWorkflowMessages(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.ReadAsyncWorkflowMessages", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorAsyncWorkflowQueueManager) ReadAsyncWorkflowMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.ReadAsyncWorkflowMessagesFromDLQRequest) (rp1 *_sourcePersistence.ReadAsyncWorkflowMessagesFromDLQResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		rp1, err = c.wrapped.ReadAsyncWorkflowMessagesFromDLQ(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.ReadAsyncWorkflowMessagesFromDLQ", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorAsyncWorkflowQueueManager) UpdateAsyncWorkflowAckLevel(ctx context.Context, request *_sourcePersistence.UpdateAsyncWorkflowAckLevelRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.UpdateAsyncWorkflowAckLevel(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "AsyncWorkflowQueueManager.UpdateAsyncWorkflowAckLevel", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}
