// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/errorinjector.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package errorinjectors

import (
	"context"
	"time"

	"github.com/uber/cadence/common/log"
	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
)

// injectorDomainAuditManager implements _sourcePersistence.DomainAuditManager interface instrumented with error injection.
type injectorDomainAuditManager struct {
	wrapped   _sourcePersistence.DomainAuditManager
	starttime time.Time
	errorRate float64
	logger    log.Logger
}

// NewDomainAuditManager creates a new instance of DomainAuditManager with error injection.
func NewDomainAuditManager(
	wrapped persistence.DomainAuditManager,
	errorRate float64,
	logger log.Logger,
	starttime time.Time,
) persistence.DomainAuditManager {
	return &injectorDomainAuditManager{
		wrapped:   wrapped,
		starttime: starttime,
		errorRate: errorRate,
		logger:    logger,
	}
}

func (c *injectorDomainAuditManager) Close() {
	c.wrapped.Close()
	return
}

func (c *injectorDomainAuditManager) CreateDomainAuditLog(ctx context.Context, request *_sourcePersistence.CreateDomainAuditLogRequest) (cp1 *_sourcePersistence.CreateDomainAuditLogResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		cp1, err = c.wrapped.CreateDomainAuditLog(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "DomainAuditManager.CreateDomainAuditLog", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorDomainAuditManager) GetDomainAuditLogs(ctx context.Context, request *_sourcePersistence.GetDomainAuditLogsRequest) (gp1 *_sourcePersistence.GetDomainAuditLogsResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		gp1, err = c.wrapped.GetDomainAuditLogs(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "DomainAuditManager.GetDomainAuditLogs", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorDomainAuditManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}
