// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/errorinjector.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package errorinjectors

import (
	"context"
	"time"

	"github.com/uber/cadence/common/log"
	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
)

// injectorSemaphoreMetadataManager implements _sourcePersistence.SemaphoreMetadataManager interface instrumented with error injection.
type injectorSemaphoreMetadataManager struct {
	wrapped   _sourcePersistence.SemaphoreMetadataManager
	starttime time.Time
	errorRate float64
	logger    log.Logger
}

// NewSemaphoreMetadataManager creates a new instance of SemaphoreMetadataManager with error injection.
func NewSemaphoreMetadataManager(
	wrapped persistence.SemaphoreMetadataManager,
	errorRate float64,
	logger log.Logger,
	starttime time.Time,
) persistence.SemaphoreMetadataManager {
	return &injectorSemaphoreMetadataManager{
		wrapped:   wrapped,
		starttime: starttime,
		errorRate: errorRate,
		logger:    logger,
	}
}

func (c *injectorSemaphoreMetadataManager) Close() {
	c.wrapped.Close()
	return
}

func (c *injectorSemaphoreMetadataManager) CreateSemaphore(ctx context.Context, request *_sourcePersistence.CreateSemaphoreRequest) (cp1 *_sourcePersistence.CreateSemaphoreResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		cp1, err = c.wrapped.CreateSemaphore(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "SemaphoreMetadataManager.CreateSemaphore", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorSemaphoreMetadataManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *injectorSemaphoreMetadataManager) GetSemaphore(ctx context.Context, request *_sourcePersistence.GetSemaphoreRequest) (gp1 *_sourcePersistence.GetSemaphoreResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		gp1, err = c.wrapped.GetSemaphore(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "SemaphoreMetadataManager.GetSemaphore", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorSemaphoreMetadataManager) ListSemaphores(ctx context.Context, request *_sourcePersistence.ListSemaphoresRequest) (lp1 *_sourcePersistence.ListSemaphoresResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		lp1, err = c.wrapped.ListSemaphores(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "SemaphoreMetadataManager.ListSemaphores", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}
