name: Pipeline Master
on:
  push:
    branches:
      - mandychen/migrate-buildkite-to-github-actions
  workflow_dispatch:
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"