name: Replication Simulation
on:
  push:
  pull_request:

jobs:
  cluster-redirection:
    name: Cluster Redirection Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Run simulation
        uses: nick-fields/retry@v3
        with:
          max_attempts: 2
          timeout_minutes: 20
          command: |
            ./simulation/replication/run.sh clusterredirection

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: cluster-redirection-test.log
          path: ./test.log

  active-active:
    name: Active-active basic checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Run simulation
        uses: nick-fields/retry@v3
        with:
          max_attempts: 2
          timeout_minutes: 20
          command: |
            ./simulation/replication/run.sh activeactive

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: active-active-test.log
          path: ./test.log
