version: "3.5"

services:
  cassandra:
    image: cassandra:4.1.1
    ports:
      - "9042:9042"
    networks:
      services-network:
        aliases:
          - cassandra
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 30s
      retries: 10

  test-cass-lwt:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command:
      - /bin/sh
      - -e
      - -c
      - >
        go test -timeout 60s
        -run ^TestCassandraLWT$
        -count 1
        -v
        -tags cassandralwt
        github.com/uber/cadence/host
        | tee test.log
    ports:
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
    environment:
      - "CASSANDRA_HOST=cassandra"
      - "CASSANDRA=1"
      - "CASSANDRA_SEEDS=cassandra"
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ../../:/cadence
    networks:
      services-network:
        aliases:
          - integration-test

networks:
  services-network:
    name: services-network
    driver: bridge
